//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class AccessControlExit : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Library_Gate fGateNumber;
        [Association(@"AccessControlExitReferencesLibrary_Gate")]
        public Library_Gate GateNumber
        {
            get { return fGateNumber; }
            set { SetPropertyValue<Library_Gate>(nameof(GateNumber), ref fGateNumber, value); }
        }
        DateTime fArrivalDateTime;
        public DateTime ArrivalDateTime
        {
            get { return fArrivalDateTime; }
            set { SetPropertyValue<DateTime>(nameof(ArrivalDateTime), ref fArrivalDateTime, value); }
        }
        DateTime fEntryDateTime;
        public DateTime EntryDateTime
        {
            get { return fEntryDateTime; }
            set { SetPropertyValue<DateTime>(nameof(EntryDateTime), ref fEntryDateTime, value); }
        }
        string fTruckRegistration;
        [Size(50)]
        public string TruckRegistration
        {
            get { return fTruckRegistration; }
            set { SetPropertyValue<string>(nameof(TruckRegistration), ref fTruckRegistration, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"AccessControlExitReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        Library_Direction fDirectionID;
        [Association(@"AccessControlExitReferencesLibrary_Direction")]
        public Library_Direction DirectionID
        {
            get { return fDirectionID; }
            set { SetPropertyValue<Library_Direction>(nameof(DirectionID), ref fDirectionID, value); }
        }
        Library_CargoType fCargoType;
        [Association(@"AccessControlExitReferencesLibrary_CargoType")]
        public Library_CargoType CargoType
        {
            get { return fCargoType; }
            set { SetPropertyValue<Library_CargoType>(nameof(CargoType), ref fCargoType, value); }
        }
        bool fContainerOnBoard;
        public bool ContainerOnBoard
        {
            get { return fContainerOnBoard; }
            set { SetPropertyValue<bool>(nameof(ContainerOnBoard), ref fContainerOnBoard, value); }
        }
        DateTime fExitDateTime;
        public DateTime ExitDateTime
        {
            get { return fExitDateTime; }
            set { SetPropertyValue<DateTime>(nameof(ExitDateTime), ref fExitDateTime, value); }
        }
        string fWBTicketNo;
        [Size(50)]
        public string WBTicketNo
        {
            get { return fWBTicketNo; }
            set { SetPropertyValue<string>(nameof(WBTicketNo), ref fWBTicketNo, value); }
        }
        int fAccessStatus;
        public int AccessStatus
        {
            get { return fAccessStatus; }
            set { SetPropertyValue<int>(nameof(AccessStatus), ref fAccessStatus, value); }
        }
        string fTruckScanReg;
        [Size(50)]
        public string TruckScanReg
        {
            get { return fTruckScanReg; }
            set { SetPropertyValue<string>(nameof(TruckScanReg), ref fTruckScanReg, value); }
        }
        string fDriverName;
        [Size(50)]
        public string DriverName
        {
            get { return fDriverName; }
            set { SetPropertyValue<string>(nameof(DriverName), ref fDriverName, value); }
        }
        byte[] fPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo
        {
            get { return fPhoto; }
            set { SetPropertyValue<byte[]>(nameof(Photo), ref fPhoto, value); }
        }
        byte[] fDriverPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] DriverPhoto
        {
            get { return fDriverPhoto; }
            set { SetPropertyValue<byte[]>(nameof(DriverPhoto), ref fDriverPhoto, value); }
        }
        byte[] fContainerPhoto1;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] ContainerPhoto1
        {
            get { return fContainerPhoto1; }
            set { SetPropertyValue<byte[]>(nameof(ContainerPhoto1), ref fContainerPhoto1, value); }
        }
        byte[] fContainerPhoto2;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] ContainerPhoto2
        {
            get { return fContainerPhoto2; }
            set { SetPropertyValue<byte[]>(nameof(ContainerPhoto2), ref fContainerPhoto2, value); }
        }
        int fNumContainers;
        public int NumContainers
        {
            get { return fNumContainers; }
            set { SetPropertyValue<int>(nameof(NumContainers), ref fNumContainers, value); }
        }
        string fConList;
        [Size(200)]
        public string ConList
        {
            get { return fConList; }
            set { SetPropertyValue<string>(nameof(ConList), ref fConList, value); }
        }
        string fContainerID;
        public string ContainerID
        {
            get { return fContainerID; }
            set { SetPropertyValue<string>(nameof(ContainerID), ref fContainerID, value); }
        }
        string fContainerValidation;
        public string ContainerValidation
        {
            get { return fContainerValidation; }
            set { SetPropertyValue<string>(nameof(ContainerValidation), ref fContainerValidation, value); }
        }
        string fContainerSeal;
        public string ContainerSeal
        {
            get { return fContainerSeal; }
            set { SetPropertyValue<string>(nameof(ContainerSeal), ref fContainerSeal, value); }
        }
    }

}
