//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class AccessControl : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Library_Gate fGateNumber;
        [Association(@"AccessControlReferencesLibrary_Gate")]
        public Library_Gate GateNumber
        {
            get { return fGateNumber; }
            set { SetPropertyValue<Library_Gate>(nameof(GateNumber), ref fGateNumber, value); }
        }
        Library_Type fAccessType;
        [Association(@"AccessControlReferencesLibrary_Type")]
        public Library_Type AccessType
        {
            get { return fAccessType; }
            set { SetPropertyValue<Library_Type>(nameof(AccessType), ref fAccessType, value); }
        }
        DateTime fArrivalDateTime;
        public DateTime ArrivalDateTime
        {
            get { return fArrivalDateTime; }
            set { SetPropertyValue<DateTime>(nameof(ArrivalDateTime), ref fArrivalDateTime, value); }
        }
        DateTime fEntryDateTime;
        public DateTime EntryDateTime
        {
            get { return fEntryDateTime; }
            set { SetPropertyValue<DateTime>(nameof(EntryDateTime), ref fEntryDateTime, value); }
        }
        string fTruckRegistration;
        [Size(50)]
        public string TruckRegistration
        {
            get { return fTruckRegistration; }
            set { SetPropertyValue<string>(nameof(TruckRegistration), ref fTruckRegistration, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"AccessControlReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        Library_Direction fDirectionID;
        [Association(@"AccessControlReferencesLibrary_Direction")]
        public Library_Direction DirectionID
        {
            get { return fDirectionID; }
            set { SetPropertyValue<Library_Direction>(nameof(DirectionID), ref fDirectionID, value); }
        }
        Library_CargoType fCargoType;
        [Association(@"AccessControlReferencesLibrary_CargoType")]
        public Library_CargoType CargoType
        {
            get { return fCargoType; }
            set { SetPropertyValue<Library_CargoType>(nameof(CargoType), ref fCargoType, value); }
        }
        bool fContainerOnBoard;
        public bool ContainerOnBoard
        {
            get { return fContainerOnBoard; }
            set { SetPropertyValue<bool>(nameof(ContainerOnBoard), ref fContainerOnBoard, value); }
        }
        bool fConfirmTruckRegistration;
        public bool ConfirmTruckRegistration
        {
            get { return fConfirmTruckRegistration; }
            set { SetPropertyValue<bool>(nameof(ConfirmTruckRegistration), ref fConfirmTruckRegistration, value); }
        }
        DateTime fExitDateTime;
        public DateTime ExitDateTime
        {
            get { return fExitDateTime; }
            set { SetPropertyValue<DateTime>(nameof(ExitDateTime), ref fExitDateTime, value); }
        }
        string fWBTicketNo;
        [Size(50)]
        public string WBTicketNo
        {
            get { return fWBTicketNo; }
            set { SetPropertyValue<string>(nameof(WBTicketNo), ref fWBTicketNo, value); }
        }
        int fAccessStatus;
        public int AccessStatus
        {
            get { return fAccessStatus; }
            set { SetPropertyValue<int>(nameof(AccessStatus), ref fAccessStatus, value); }
        }
        string fTruckScan;
        [Size(50)]
        public string TruckScan
        {
            get { return fTruckScan; }
            set { SetPropertyValue<string>(nameof(TruckScan), ref fTruckScan, value); }
        }
        string fDriverName;
        [Size(50)]
        public string DriverName
        {
            get { return fDriverName; }
            set { SetPropertyValue<string>(nameof(DriverName), ref fDriverName, value); }
        }
        string fConList;
        [Size(200)]
        public string ConList
        {
            get { return fConList; }
            set { SetPropertyValue<string>(nameof(ConList), ref fConList, value); }
        }
        byte[] fPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo
        {
            get { return fPhoto; }
            set { SetPropertyValue<byte[]>(nameof(Photo), ref fPhoto, value); }
        }
        byte[] fDriverPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] DriverPhoto
        {
            get { return fDriverPhoto; }
            set { SetPropertyValue<byte[]>(nameof(DriverPhoto), ref fDriverPhoto, value); }
        }
        string fContainerID;
        public string ContainerID
        {
            get { return fContainerID; }
            set { SetPropertyValue<string>(nameof(ContainerID), ref fContainerID, value); }
        }
        string fContainerValidation;
        public string ContainerValidation
        {
            get { return fContainerValidation; }
            set { SetPropertyValue<string>(nameof(ContainerValidation), ref fContainerValidation, value); }
        }
        string fContainerSeal;
        public string ContainerSeal
        {
            get { return fContainerSeal; }
            set { SetPropertyValue<string>(nameof(ContainerSeal), ref fContainerSeal, value); }
        }
        int fNumContainers;
        public int NumContainers
        {
            get { return fNumContainers; }
            set { SetPropertyValue<int>(nameof(NumContainers), ref fNumContainers, value); }
        }
        int fFlag;
        public int Flag
        {
            get { return fFlag; }
            set { SetPropertyValue<int>(nameof(Flag), ref fFlag, value); }
        }
        Container fContainer1ID;
        [Association(@"AccessControlReferencesContainer")]
        public Container Container1ID
        {
            get { return fContainer1ID; }
            set { SetPropertyValue<Container>(nameof(Container1ID), ref fContainer1ID, value); }
        }
        string fContainer1Seal;
        [Size(10)]
        public string Container1Seal
        {
            get { return fContainer1Seal; }
            set { SetPropertyValue<string>(nameof(Container1Seal), ref fContainer1Seal, value); }
        }
        string fContainer2Seal;
        [Size(10)]
        public string Container2Seal
        {
            get { return fContainer2Seal; }
            set { SetPropertyValue<string>(nameof(Container2Seal), ref fContainer2Seal, value); }
        }
        Container fContainer2ID;
        [Association(@"AccessControlReferencesContainer1")]
        public Container Container2ID
        {
            get { return fContainer2ID; }
            set { SetPropertyValue<Container>(nameof(Container2ID), ref fContainer2ID, value); }
        }
        string fContainer3Seal;
        [Size(10)]
        public string Container3Seal
        {
            get { return fContainer3Seal; }
            set { SetPropertyValue<string>(nameof(Container3Seal), ref fContainer3Seal, value); }
        }
        Container fContainer3ID;
        [Association(@"AccessControlReferencesContainer2")]
        public Container Container3ID
        {
            get { return fContainer3ID; }
            set { SetPropertyValue<Container>(nameof(Container3ID), ref fContainer3ID, value); }
        }
        [Association(@"ContainerReferencesAccessControl")]
        public XPCollection<Container> Containers { get { return GetCollection<Container>(nameof(Containers)); } }
        [Association(@"Container_EmptyInReferencesAccessControl")]
        public XPCollection<Container_EmptyIn> Container_EmptyIns { get { return GetCollection<Container_EmptyIn>(nameof(Container_EmptyIns)); } }
        [Association(@"Product_ProductDispatchReferencesAccessControl")]
        public XPCollection<Product_ProductDispatch> Product_ProductDispatchs { get { return GetCollection<Product_ProductDispatch>(nameof(Product_ProductDispatchs)); } }
        [Association(@"Product_ProductReceiveReferencesAccessControl")]
        public XPCollection<Product_ProductReceive> Product_ProductReceives { get { return GetCollection<Product_ProductReceive>(nameof(Product_ProductReceives)); } }
    }

}
