//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class BlockWeigh : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Library_Weighbridge fWeighbridgeID;
        [Association(@"BlockWeighReferencesLibrary_Weighbridge")]
        public Library_Weighbridge WeighbridgeID
        {
            get { return fWeighbridgeID; }
            set { SetPropertyValue<Library_Weighbridge>(nameof(WeighbridgeID), ref fWeighbridgeID, value); }
        }
        int fBlockWeightGross;
        public int BlockWeightGross
        {
            get { return fBlockWeightGross; }
            set { SetPropertyValue<int>(nameof(BlockWeightGross), ref fBlockWeightGross, value); }
        }
        double fBlockWeightTar;
        public double BlockWeightTar
        {
            get { return fBlockWeightTar; }
            set { SetPropertyValue<double>(nameof(BlockWeightTar), ref fBlockWeightTar, value); }
        }
        DateTime fDateWeighed;
        public DateTime DateWeighed
        {
            get { return fDateWeighed; }
            set { SetPropertyValue<DateTime>(nameof(DateWeighed), ref fDateWeighed, value); }
        }
        double fNettWeight;
        public double NettWeight
        {
            get { return fNettWeight; }
            set { SetPropertyValue<double>(nameof(NettWeight), ref fNettWeight, value); }
        }
        string fComment;
        [Size(SizeAttribute.Unlimited)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
    }

}
