//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Brereton : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fBarcode;
        [Size(50)]
        public string Barcode
        {
            get { return fBarcode; }
            set { SetPropertyValue<string>(nameof(Barcode), ref fBarcode, value); }
        }
        int fDiameter1;
        public int Diameter1
        {
            get { return fDiameter1; }
            set { SetPropertyValue<int>(nameof(Diameter1), ref fDiameter1, value); }
        }
        int fDiameter2;
        public int Diameter2
        {
            get { return fDiameter2; }
            set { SetPropertyValue<int>(nameof(Diameter2), ref fDiameter2, value); }
        }
        int fDiameter3;
        public int Diameter3
        {
            get { return fDiameter3; }
            set { SetPropertyValue<int>(nameof(Diameter3), ref fDiameter3, value); }
        }
        int fDiameter4;
        public int Diameter4
        {
            get { return fDiameter4; }
            set { SetPropertyValue<int>(nameof(Diameter4), ref fDiameter4, value); }
        }
        int fFlag;
        public int Flag
        {
            get { return fFlag; }
            set { SetPropertyValue<int>(nameof(Flag), ref fFlag, value); }
        }
        string fBarcodeScan;
        [Size(50)]
        public string BarcodeScan
        {
            get { return fBarcodeScan; }
            set { SetPropertyValue<string>(nameof(BarcodeScan), ref fBarcodeScan, value); }
        }
    }

}
