//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(AccessControl),
            typeof(AccessControlExit),
            typeof(Analysis),
            typeof(AuditDataItemPersistent),
            typeof(AuditedObjectWeakReference),
            typeof(BlockWeigh),
            typeof(BookingReference_ProductDispatch),
            typeof(BookingReference_ProductDispatch_Lte),
            typeof(Brereton),
            typeof(Container),
            typeof(Container_BookingTransfer),
            typeof(Container_EmptyIn),
            typeof(Container_EmptyOut),
            typeof(Container_FullIn),
            typeof(Container_FullOut),
            typeof(Container_Packed),
            typeof(Container_Transfer),
            typeof(Container_Trim),
            typeof(DashboardData),
            typeof(Document_BookingReference),
            typeof(Document_Orders),
            typeof(Event),
            typeof(ExpectedProductItem),
            typeof(ExpectedTrucks),
            typeof(FileData),
            typeof(HatchScan),
            typeof(HCategory),
            typeof(Incident),
            typeof(Invoice),
            typeof(ItemInspection),
            typeof(KpiDefinition),
            typeof(KpiHistoryItem),
            typeof(KpiInstance),
            typeof(KpiScorecard),
            typeof(KpiScorecardScorecards_KpiInstanceIndicators),
            typeof(Library_BookingType),
            typeof(Library_CargoType),
            typeof(Library_Charterer),
            typeof(Library_Client),
            typeof(Library_ContainerSize),
            typeof(Library_ContainerStatus),
            typeof(Library_DestinationType),
            typeof(Library_Direction),
            typeof(Library_DocumentCategory),
            typeof(Library_Gate),
            typeof(Library_Grade),
            typeof(Library_HandlingPoint),
            typeof(Library_IncidentCause),
            typeof(Library_IncidentType),
            typeof(Library_InspectionCompany),
            typeof(Library_Length),
            typeof(Library_Material),
            typeof(Library_OrderType),
            typeof(Library_OriginType),
            typeof(Library_Packaging),
            typeof(Library_Product),
            typeof(Library_ProductType),
            typeof(Library_RCMClient),
            typeof(Library_Sampler),
            typeof(Library_SealCondition),
            typeof(Library_ShippingAgent),
            typeof(Library_Siding),
            typeof(Library_Site),
            typeof(Library_Status),
            typeof(Library_Supplier),
            typeof(Library_TarpCondition),
            typeof(Library_Terminal),
            typeof(Library_Transporter),
            typeof(Library_TransporterType),
            typeof(Library_TransportType),
            typeof(Library_TrimAction),
            typeof(Library_TruckType),
            typeof(Library_Type),
            typeof(Library_UnitOfMeasure),
            typeof(Library_Vessel),
            typeof(Library_Weather),
            typeof(Library_Weighbridge),
            typeof(Library_WeighMethod),
            typeof(ModelDifference),
            typeof(ModelDifferenceAspect),
            typeof(Order_BookingReference),
            typeof(Order_OrderIn),
            typeof(Order_OrderOut),
            typeof(Order_VesselHatch),
            typeof(Order_VesselIntake),
            typeof(PermissionPolicyMemberPermissionsObject),
            typeof(PermissionPolicyNavigationPermissionsObject),
            typeof(PermissionPolicyObjectPermissionsObject),
            typeof(PermissionPolicyRole),
            typeof(PermissionPolicyTypePermissionsObject),
            typeof(PermissionPolicyUser),
            typeof(PermissionPolicyUserUsers_PermissionPolicyRoleRoles),
            typeof(Product_Dispatch_Rail),
            typeof(Product_ProductDispatch),
            typeof(Product_ProductItem),
            typeof(Product_ProductReceive),
            typeof(Product_Receive_Rail),
            typeof(Product_ReceiveCount),
            typeof(ProductItemPickList),
            typeof(ReportDataV2),
            typeof(Resource),
            typeof(ResourceResources_EventEvents),
            typeof(ShuttleTrucks),
            typeof(StockHandling),
            typeof(Template_Document),
            typeof(TruckStopEntry),
            typeof(TruckStopExit),
            typeof(WagonConsignment)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public static string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings["DESKTOP-32QVBUVSQL2017RapidCM_PGS_Dev"].ConnectionString; } }
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
