//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Container_EmptyOut : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Container fContainerID;
        [Association(@"Container_EmptyOutReferencesContainer")]
        public Container ContainerID
        {
            get { return fContainerID; }
            set { SetPropertyValue<Container>(nameof(ContainerID), ref fContainerID, value); }
        }
        int fDispOrderID;
        [Indexed(Name = @"iDispOrderID_Container_EmptyOut")]
        public int DispOrderID
        {
            get { return fDispOrderID; }
            set { SetPropertyValue<int>(nameof(DispOrderID), ref fDispOrderID, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"Container_EmptyOutReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        string fTruckRegistration;
        [Size(50)]
        public string TruckRegistration
        {
            get { return fTruckRegistration; }
            set { SetPropertyValue<string>(nameof(TruckRegistration), ref fTruckRegistration, value); }
        }
        string fTrailer1Registration;
        [Size(50)]
        public string Trailer1Registration
        {
            get { return fTrailer1Registration; }
            set { SetPropertyValue<string>(nameof(Trailer1Registration), ref fTrailer1Registration, value); }
        }
        DateTime fDateOut;
        public DateTime DateOut
        {
            get { return fDateOut; }
            set { SetPropertyValue<DateTime>(nameof(DateOut), ref fDateOut, value); }
        }
        string fDestination;
        [Size(50)]
        public string Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<string>(nameof(Destination), ref fDestination, value); }
        }
        double fTarWeight;
        public double TarWeight
        {
            get { return fTarWeight; }
            set { SetPropertyValue<double>(nameof(TarWeight), ref fTarWeight, value); }
        }
        DateTime fTarWeightDate;
        public DateTime TarWeightDate
        {
            get { return fTarWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(TarWeightDate), ref fTarWeightDate, value); }
        }
        string fDestinationDepot;
        [Size(50)]
        public string DestinationDepot
        {
            get { return fDestinationDepot; }
            set { SetPropertyValue<string>(nameof(DestinationDepot), ref fDestinationDepot, value); }
        }
        Library_Site fSiteID;
        [Association(@"Container_EmptyOutReferencesLibrary_Site")]
        public Library_Site SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<Library_Site>(nameof(SiteID), ref fSiteID, value); }
        }
        Library_Weighbridge fWeighbridgeID;
        [Association(@"Container_EmptyOutReferencesLibrary_Weighbridge")]
        public Library_Weighbridge WeighbridgeID
        {
            get { return fWeighbridgeID; }
            set { SetPropertyValue<Library_Weighbridge>(nameof(WeighbridgeID), ref fWeighbridgeID, value); }
        }
        Order_BookingReference fBookingReferenceID;
        [Association(@"Container_EmptyOutReferencesOrder_BookingReference")]
        public Order_BookingReference BookingReferenceID
        {
            get { return fBookingReferenceID; }
            set { SetPropertyValue<Order_BookingReference>(nameof(BookingReferenceID), ref fBookingReferenceID, value); }
        }
        int feFlag;
        public int eFlag
        {
            get { return feFlag; }
            set { SetPropertyValue<int>(nameof(eFlag), ref feFlag, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        Container_EmptyIn fEmptyID;
        [Association(@"Container_EmptyOutReferencesContainer_EmptyIn")]
        public Container_EmptyIn EmptyID
        {
            get { return fEmptyID; }
            set { SetPropertyValue<Container_EmptyIn>(nameof(EmptyID), ref fEmptyID, value); }
        }
        double fGrossWeight;
        public double GrossWeight
        {
            get { return fGrossWeight; }
            set { SetPropertyValue<double>(nameof(GrossWeight), ref fGrossWeight, value); }
        }
        DateTime fGrossWeightDate;
        public DateTime GrossWeightDate
        {
            get { return fGrossWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(GrossWeightDate), ref fGrossWeightDate, value); }
        }
        double fContainerNettWeight;
        public double ContainerNettWeight
        {
            get { return fContainerNettWeight; }
            set { SetPropertyValue<double>(nameof(ContainerNettWeight), ref fContainerNettWeight, value); }
        }
    }

}
