//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Container_Packed : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        double fContainerGrossWeight;
        public double ContainerGrossWeight
        {
            get { return fContainerGrossWeight; }
            set { SetPropertyValue<double>(nameof(ContainerGrossWeight), ref fContainerGrossWeight, value); }
        }
        DateTime fDateEmptyIn;
        public DateTime DateEmptyIn
        {
            get { return fDateEmptyIn; }
            set { SetPropertyValue<DateTime>(nameof(DateEmptyIn), ref fDateEmptyIn, value); }
        }
        DateTime fGrossWeightDate;
        public DateTime GrossWeightDate
        {
            get { return fGrossWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(GrossWeightDate), ref fGrossWeightDate, value); }
        }
        double fContainerNettWeight;
        public double ContainerNettWeight
        {
            get { return fContainerNettWeight; }
            set { SetPropertyValue<double>(nameof(ContainerNettWeight), ref fContainerNettWeight, value); }
        }
        DateTime fDatePacked;
        public DateTime DatePacked
        {
            get { return fDatePacked; }
            set { SetPropertyValue<DateTime>(nameof(DatePacked), ref fDatePacked, value); }
        }
        DateTime fDateDispatched;
        public DateTime DateDispatched
        {
            get { return fDateDispatched; }
            set { SetPropertyValue<DateTime>(nameof(DateDispatched), ref fDateDispatched, value); }
        }
        string fSamplingSeal;
        [Size(50)]
        public string SamplingSeal
        {
            get { return fSamplingSeal; }
            set { SetPropertyValue<string>(nameof(SamplingSeal), ref fSamplingSeal, value); }
        }
        string fItemBarcode;
        [Size(50)]
        public string ItemBarcode
        {
            get { return fItemBarcode; }
            set { SetPropertyValue<string>(nameof(ItemBarcode), ref fItemBarcode, value); }
        }
        string fScanValidation;
        [Size(50)]
        public string ScanValidation
        {
            get { return fScanValidation; }
            set { SetPropertyValue<string>(nameof(ScanValidation), ref fScanValidation, value); }
        }
        string fLineSeal;
        [Size(50)]
        public string LineSeal
        {
            get { return fLineSeal; }
            set { SetPropertyValue<string>(nameof(LineSeal), ref fLineSeal, value); }
        }
        Library_Site fSiteID;
        [Association(@"Container_PackedReferencesLibrary_Site")]
        public Library_Site SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<Library_Site>(nameof(SiteID), ref fSiteID, value); }
        }
        Order_BookingReference fBookingReferenceID;
        [Association(@"Container_PackedReferencesOrder_BookingReference")]
        public Order_BookingReference BookingReferenceID
        {
            get { return fBookingReferenceID; }
            set { SetPropertyValue<Order_BookingReference>(nameof(BookingReferenceID), ref fBookingReferenceID, value); }
        }
        Library_Weighbridge fWeighbridgeID;
        [Association(@"Container_PackedReferencesLibrary_Weighbridge")]
        public Library_Weighbridge WeighbridgeID
        {
            get { return fWeighbridgeID; }
            set { SetPropertyValue<Library_Weighbridge>(nameof(WeighbridgeID), ref fWeighbridgeID, value); }
        }
        Container fContainerID;
        [Association(@"Container_PackedReferencesContainer")]
        public Container ContainerID
        {
            get { return fContainerID; }
            set { SetPropertyValue<Container>(nameof(ContainerID), ref fContainerID, value); }
        }
        ProductItemPickList fPicklistID;
        [Association(@"Container_PackedReferencesProductItemPickList")]
        public ProductItemPickList PicklistID
        {
            get { return fPicklistID; }
            set { SetPropertyValue<ProductItemPickList>(nameof(PicklistID), ref fPicklistID, value); }
        }
        int fPFlag;
        public int PFlag
        {
            get { return fPFlag; }
            set { SetPropertyValue<int>(nameof(PFlag), ref fPFlag, value); }
        }
        double fContainerTar;
        public double ContainerTar
        {
            get { return fContainerTar; }
            set { SetPropertyValue<double>(nameof(ContainerTar), ref fContainerTar, value); }
        }
        double fContainerScaleTar;
        public double ContainerScaleTar
        {
            get { return fContainerScaleTar; }
            set { SetPropertyValue<double>(nameof(ContainerScaleTar), ref fContainerScaleTar, value); }
        }
        int fNoBagsPacked;
        public int NoBagsPacked
        {
            get { return fNoBagsPacked; }
            set { SetPropertyValue<int>(nameof(NoBagsPacked), ref fNoBagsPacked, value); }
        }
        int feFlag;
        public int eFlag
        {
            get { return feFlag; }
            set { SetPropertyValue<int>(nameof(eFlag), ref feFlag, value); }
        }
        byte[] fPhoto3;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo3
        {
            get { return fPhoto3; }
            set { SetPropertyValue<byte[]>(nameof(Photo3), ref fPhoto3, value); }
        }
        byte[] fPhoto4;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo4
        {
            get { return fPhoto4; }
            set { SetPropertyValue<byte[]>(nameof(Photo4), ref fPhoto4, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        Library_Weather fWeatherID;
        [Association(@"Container_PackedReferencesLibrary_Weather")]
        public Library_Weather WeatherID
        {
            get { return fWeatherID; }
            set { SetPropertyValue<Library_Weather>(nameof(WeatherID), ref fWeatherID, value); }
        }
        string fComment;
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        byte[] fPhoto1;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo1
        {
            get { return fPhoto1; }
            set { SetPropertyValue<byte[]>(nameof(Photo1), ref fPhoto1, value); }
        }
        byte[] fPhoto2;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo2
        {
            get { return fPhoto2; }
            set { SetPropertyValue<byte[]>(nameof(Photo2), ref fPhoto2, value); }
        }
        bool fDone;
        public bool Done
        {
            get { return fDone; }
            set { SetPropertyValue<bool>(nameof(Done), ref fDone, value); }
        }
        string fBarcodeList;
        public string BarcodeList
        {
            get { return fBarcodeList; }
            set { SetPropertyValue<string>(nameof(BarcodeList), ref fBarcodeList, value); }
        }
        Library_Grade fGradeID;
        [Association(@"Container_PackedReferencesLibrary_Grade")]
        public Library_Grade GradeID
        {
            get { return fGradeID; }
            set { SetPropertyValue<Library_Grade>(nameof(GradeID), ref fGradeID, value); }
        }
        Library_Supplier fSupplierID;
        [Association(@"Container_PackedReferencesLibrary_Supplier")]
        public Library_Supplier SupplierID
        {
            get { return fSupplierID; }
            set { SetPropertyValue<Library_Supplier>(nameof(SupplierID), ref fSupplierID, value); }
        }
        string fLogScan;
        [Size(SizeAttribute.Unlimited)]
        public string LogScan
        {
            get { return fLogScan; }
            set { SetPropertyValue<string>(nameof(LogScan), ref fLogScan, value); }
        }
        byte[] fPhoto5;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo5
        {
            get { return fPhoto5; }
            set { SetPropertyValue<byte[]>(nameof(Photo5), ref fPhoto5, value); }
        }
        byte[] fPhoto6;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo6
        {
            get { return fPhoto6; }
            set { SetPropertyValue<byte[]>(nameof(Photo6), ref fPhoto6, value); }
        }
        byte[] fPhoto7;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo7
        {
            get { return fPhoto7; }
            set { SetPropertyValue<byte[]>(nameof(Photo7), ref fPhoto7, value); }
        }
        byte[] fPhoto8;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo8
        {
            get { return fPhoto8; }
            set { SetPropertyValue<byte[]>(nameof(Photo8), ref fPhoto8, value); }
        }
        DateTime fDateModified;
        public DateTime DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime>(nameof(DateModified), ref fDateModified, value); }
        }
        string fAllScan;
        [Size(SizeAttribute.Unlimited)]
        public string AllScan
        {
            get { return fAllScan; }
            set { SetPropertyValue<string>(nameof(AllScan), ref fAllScan, value); }
        }
        string fWBTicketNo;
        public string WBTicketNo
        {
            get { return fWBTicketNo; }
            set { SetPropertyValue<string>(nameof(WBTicketNo), ref fWBTicketNo, value); }
        }
        string fGDN;
        public string GDN
        {
            get { return fGDN; }
            set { SetPropertyValue<string>(nameof(GDN), ref fGDN, value); }
        }
        bool fLockTran;
        public bool LockTran
        {
            get { return fLockTran; }
            set { SetPropertyValue<bool>(nameof(LockTran), ref fLockTran, value); }
        }
        int fLogCount;
        public int LogCount
        {
            get { return fLogCount; }
            set { SetPropertyValue<int>(nameof(LogCount), ref fLogCount, value); }
        }
        [Association(@"BookingReference_ProductDispatch_LteReferencesContainer_Packed")]
        public XPCollection<BookingReference_ProductDispatch_Lte> BookingReference_ProductDispatch_Ltes { get { return GetCollection<BookingReference_ProductDispatch_Lte>(nameof(BookingReference_ProductDispatch_Ltes)); } }
        [Association(@"Product_ProductItemReferencesContainer_Packed")]
        public XPCollection<Product_ProductItem> Product_ProductItems { get { return GetCollection<Product_ProductItem>(nameof(Product_ProductItems)); } }
    }

}
