//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Container_FullOut : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        int fDispOrderID;
        public int DispOrderID
        {
            get { return fDispOrderID; }
            set { SetPropertyValue<int>(nameof(DispOrderID), ref fDispOrderID, value); }
        }
        double fContainerGrossWeight;
        public double ContainerGrossWeight
        {
            get { return fContainerGrossWeight; }
            set { SetPropertyValue<double>(nameof(ContainerGrossWeight), ref fContainerGrossWeight, value); }
        }
        double fContainerNettWeight;
        public double ContainerNettWeight
        {
            get { return fContainerNettWeight; }
            set { SetPropertyValue<double>(nameof(ContainerNettWeight), ref fContainerNettWeight, value); }
        }
        DateTime fDateOut;
        public DateTime DateOut
        {
            get { return fDateOut; }
            set { SetPropertyValue<DateTime>(nameof(DateOut), ref fDateOut, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"Container_FullOutReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        string fTruckRegistration;
        [Size(50)]
        public string TruckRegistration
        {
            get { return fTruckRegistration; }
            set { SetPropertyValue<string>(nameof(TruckRegistration), ref fTruckRegistration, value); }
        }
        string fTrailer1Registration;
        [Size(50)]
        public string Trailer1Registration
        {
            get { return fTrailer1Registration; }
            set { SetPropertyValue<string>(nameof(Trailer1Registration), ref fTrailer1Registration, value); }
        }
        string fTrailer2Registration;
        [Size(50)]
        public string Trailer2Registration
        {
            get { return fTrailer2Registration; }
            set { SetPropertyValue<string>(nameof(Trailer2Registration), ref fTrailer2Registration, value); }
        }
        string fTransporterDel;
        [Size(50)]
        public string TransporterDel
        {
            get { return fTransporterDel; }
            set { SetPropertyValue<string>(nameof(TransporterDel), ref fTransporterDel, value); }
        }
        string fCTO;
        [Size(50)]
        public string CTO
        {
            get { return fCTO; }
            set { SetPropertyValue<string>(nameof(CTO), ref fCTO, value); }
        }
        Library_Site fSiteID;
        [Association(@"Container_FullOutReferencesLibrary_Site")]
        public Library_Site SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<Library_Site>(nameof(SiteID), ref fSiteID, value); }
        }
        Library_Weighbridge fWeighbridgeID;
        [Association(@"Container_FullOutReferencesLibrary_Weighbridge")]
        public Library_Weighbridge WeighbridgeID
        {
            get { return fWeighbridgeID; }
            set { SetPropertyValue<Library_Weighbridge>(nameof(WeighbridgeID), ref fWeighbridgeID, value); }
        }
        Order_BookingReference fBookingReferenceID;
        [Association(@"Container_FullOutReferencesOrder_BookingReference")]
        public Order_BookingReference BookingReferenceID
        {
            get { return fBookingReferenceID; }
            set { SetPropertyValue<Order_BookingReference>(nameof(BookingReferenceID), ref fBookingReferenceID, value); }
        }
        Container fContainerID;
        [Association(@"Container_FullOutReferencesContainer")]
        public Container ContainerID
        {
            get { return fContainerID; }
            set { SetPropertyValue<Container>(nameof(ContainerID), ref fContainerID, value); }
        }
        double fGrossWeight;
        public double GrossWeight
        {
            get { return fGrossWeight; }
            set { SetPropertyValue<double>(nameof(GrossWeight), ref fGrossWeight, value); }
        }
        double fContainerScaleTar;
        public double ContainerScaleTar
        {
            get { return fContainerScaleTar; }
            set { SetPropertyValue<double>(nameof(ContainerScaleTar), ref fContainerScaleTar, value); }
        }
        double fTruckScale;
        public double TruckScale
        {
            get { return fTruckScale; }
            set { SetPropertyValue<double>(nameof(TruckScale), ref fTruckScale, value); }
        }
        int fSAP_No;
        public int SAP_No
        {
            get { return fSAP_No; }
            set { SetPropertyValue<int>(nameof(SAP_No), ref fSAP_No, value); }
        }
        Library_TransportType fTransportMethodID;
        [Association(@"Container_FullOutReferencesLibrary_TransportType")]
        public Library_TransportType TransportMethodID
        {
            get { return fTransportMethodID; }
            set { SetPropertyValue<Library_TransportType>(nameof(TransportMethodID), ref fTransportMethodID, value); }
        }
        int feFlag;
        public int eFlag
        {
            get { return feFlag; }
            set { SetPropertyValue<int>(nameof(eFlag), ref feFlag, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        string fSealNumber;
        [Size(50)]
        public string SealNumber
        {
            get { return fSealNumber; }
            set { SetPropertyValue<string>(nameof(SealNumber), ref fSealNumber, value); }
        }
    }

}
