//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Container_Trim : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Container fContainerID;
        [Association(@"Container_TrimReferencesContainer")]
        public Container ContainerID
        {
            get { return fContainerID; }
            set { SetPropertyValue<Container>(nameof(ContainerID), ref fContainerID, value); }
        }
        Library_TrimAction fTrimActionID;
        [Association(@"Container_TrimReferencesLibrary_TrimAction")]
        public Library_TrimAction TrimActionID
        {
            get { return fTrimActionID; }
            set { SetPropertyValue<Library_TrimAction>(nameof(TrimActionID), ref fTrimActionID, value); }
        }
        string fScanList;
        [Size(SizeAttribute.Unlimited)]
        public string ScanList
        {
            get { return fScanList; }
            set { SetPropertyValue<string>(nameof(ScanList), ref fScanList, value); }
        }
        DateTime fTrimDate;
        public DateTime TrimDate
        {
            get { return fTrimDate; }
            set { SetPropertyValue<DateTime>(nameof(TrimDate), ref fTrimDate, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        DateTime fDateModified;
        public DateTime DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime>(nameof(DateModified), ref fDateModified, value); }
        }
    }

}
