//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Container : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fContainerNo;
        [Size(15)]
        public string ContainerNo
        {
            get { return fContainerNo; }
            set { SetPropertyValue<string>(nameof(ContainerNo), ref fContainerNo, value); }
        }
        double fContainerVGM;
        public double ContainerVGM
        {
            get { return fContainerVGM; }
            set { SetPropertyValue<double>(nameof(ContainerVGM), ref fContainerVGM, value); }
        }
        double fContainerMAXP;
        public double ContainerMAXP
        {
            get { return fContainerMAXP; }
            set { SetPropertyValue<double>(nameof(ContainerMAXP), ref fContainerMAXP, value); }
        }
        Library_ContainerSize fContainerSizeID;
        [Association(@"ContainerReferencesLibrary_ContainerSize")]
        public Library_ContainerSize ContainerSizeID
        {
            get { return fContainerSizeID; }
            set { SetPropertyValue<Library_ContainerSize>(nameof(ContainerSizeID), ref fContainerSizeID, value); }
        }
        double fContainerTar;
        public double ContainerTar
        {
            get { return fContainerTar; }
            set { SetPropertyValue<double>(nameof(ContainerTar), ref fContainerTar, value); }
        }
        int fContainerStatus;
        public int ContainerStatus
        {
            get { return fContainerStatus; }
            set { SetPropertyValue<int>(nameof(ContainerStatus), ref fContainerStatus, value); }
        }
        string fStatus;
        [Size(50)]
        public string Status
        {
            get { return fStatus; }
            set { SetPropertyValue<string>(nameof(Status), ref fStatus, value); }
        }
        Order_BookingReference fCurrentBookingRefID;
        [Association(@"ContainerReferencesOrder_BookingReference")]
        public Order_BookingReference CurrentBookingRefID
        {
            get { return fCurrentBookingRefID; }
            set { SetPropertyValue<Order_BookingReference>(nameof(CurrentBookingRefID), ref fCurrentBookingRefID, value); }
        }
        DateTime fStatusDate;
        public DateTime StatusDate
        {
            get { return fStatusDate; }
            set { SetPropertyValue<DateTime>(nameof(StatusDate), ref fStatusDate, value); }
        }
        string fContainerSeal;
        [Size(10)]
        public string ContainerSeal
        {
            get { return fContainerSeal; }
            set { SetPropertyValue<string>(nameof(ContainerSeal), ref fContainerSeal, value); }
        }
        int fTempAccessID;
        public int TempAccessID
        {
            get { return fTempAccessID; }
            set { SetPropertyValue<int>(nameof(TempAccessID), ref fTempAccessID, value); }
        }
        byte[] fPhoto1;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo1
        {
            get { return fPhoto1; }
            set { SetPropertyValue<byte[]>(nameof(Photo1), ref fPhoto1, value); }
        }
        byte[] fPhoto2;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo2
        {
            get { return fPhoto2; }
            set { SetPropertyValue<byte[]>(nameof(Photo2), ref fPhoto2, value); }
        }
        int fCheckVal;
        public int CheckVal
        {
            get { return fCheckVal; }
            set { SetPropertyValue<int>(nameof(CheckVal), ref fCheckVal, value); }
        }
        AccessControl fAccessID;
        [Association(@"ContainerReferencesAccessControl")]
        public AccessControl AccessID
        {
            get { return fAccessID; }
            set { SetPropertyValue<AccessControl>(nameof(AccessID), ref fAccessID, value); }
        }
        string fTempKey;
        [Size(50)]
        public string TempKey
        {
            get { return fTempKey; }
            set { SetPropertyValue<string>(nameof(TempKey), ref fTempKey, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        DateTime fDateModified;
        public DateTime DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime>(nameof(DateModified), ref fDateModified, value); }
        }
        int fPodNumber;
        public int PodNumber
        {
            get { return fPodNumber; }
            set { SetPropertyValue<int>(nameof(PodNumber), ref fPodNumber, value); }
        }
        byte[] fPodPicture;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] PodPicture
        {
            get { return fPodPicture; }
            set { SetPropertyValue<byte[]>(nameof(PodPicture), ref fPodPicture, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"ContainerReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        [Association(@"AccessControlReferencesContainer")]
        public XPCollection<AccessControl> AccessControls { get { return GetCollection<AccessControl>(nameof(AccessControls)); } }
        [Association(@"AccessControlReferencesContainer1")]
        public XPCollection<AccessControl> AccessControls1 { get { return GetCollection<AccessControl>(nameof(AccessControls1)); } }
        [Association(@"AccessControlReferencesContainer2")]
        public XPCollection<AccessControl> AccessControls2 { get { return GetCollection<AccessControl>(nameof(AccessControls2)); } }
        [Association(@"BookingReference_ProductDispatchReferencesContainer")]
        public XPCollection<BookingReference_ProductDispatch> BookingReference_ProductDispatchs { get { return GetCollection<BookingReference_ProductDispatch>(nameof(BookingReference_ProductDispatchs)); } }
        [Association(@"Container_BookingTransferReferencesContainer")]
        public XPCollection<Container_BookingTransfer> Container_BookingTransfers { get { return GetCollection<Container_BookingTransfer>(nameof(Container_BookingTransfers)); } }
        [Association(@"Container_EmptyInReferencesContainer")]
        public XPCollection<Container_EmptyIn> Container_EmptyIns { get { return GetCollection<Container_EmptyIn>(nameof(Container_EmptyIns)); } }
        [Association(@"Container_EmptyOutReferencesContainer")]
        public XPCollection<Container_EmptyOut> Container_EmptyOuts { get { return GetCollection<Container_EmptyOut>(nameof(Container_EmptyOuts)); } }
        [Association(@"Container_FullInReferencesContainer")]
        public XPCollection<Container_FullIn> Container_FullIns { get { return GetCollection<Container_FullIn>(nameof(Container_FullIns)); } }
        [Association(@"Container_FullOutReferencesContainer")]
        public XPCollection<Container_FullOut> Container_FullOuts { get { return GetCollection<Container_FullOut>(nameof(Container_FullOuts)); } }
        [Association(@"Container_PackedReferencesContainer")]
        public XPCollection<Container_Packed> Container_Packeds { get { return GetCollection<Container_Packed>(nameof(Container_Packeds)); } }
        [Association(@"Container_TrimReferencesContainer")]
        public XPCollection<Container_Trim> Container_Trims { get { return GetCollection<Container_Trim>(nameof(Container_Trims)); } }
    }

}
