//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Container_Transfer : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        int fContainerID;
        [Indexed(Name = @"iContainerID_Container_Transfer")]
        public int ContainerID
        {
            get { return fContainerID; }
            set { SetPropertyValue<int>(nameof(ContainerID), ref fContainerID, value); }
        }
        Order_BookingReference fBookingRefFrom;
        [Association(@"Container_TransferReferencesOrder_BookingReference")]
        public Order_BookingReference BookingRefFrom
        {
            get { return fBookingRefFrom; }
            set { SetPropertyValue<Order_BookingReference>(nameof(BookingRefFrom), ref fBookingRefFrom, value); }
        }
        string fTransferReason;
        [Size(300)]
        public string TransferReason
        {
            get { return fTransferReason; }
            set { SetPropertyValue<string>(nameof(TransferReason), ref fTransferReason, value); }
        }
        Order_BookingReference fBookingRefTo;
        [Association(@"Container_TransferReferencesOrder_BookingReference1")]
        public Order_BookingReference BookingRefTo
        {
            get { return fBookingRefTo; }
            set { SetPropertyValue<Order_BookingReference>(nameof(BookingRefTo), ref fBookingRefTo, value); }
        }
        DateTime fTransferDate;
        public DateTime TransferDate
        {
            get { return fTransferDate; }
            set { SetPropertyValue<DateTime>(nameof(TransferDate), ref fTransferDate, value); }
        }
    }

}
