//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class ExpectedTrucks : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fTruckRegistration;
        [Size(50)]
        public string TruckRegistration
        {
            get { return fTruckRegistration; }
            set { SetPropertyValue<string>(nameof(TruckRegistration), ref fTruckRegistration, value); }
        }
        string fTrailer1Registration;
        [Size(50)]
        public string Trailer1Registration
        {
            get { return fTrailer1Registration; }
            set { SetPropertyValue<string>(nameof(Trailer1Registration), ref fTrailer1Registration, value); }
        }
        string fTrailer2Registration;
        [Size(50)]
        public string Trailer2Registration
        {
            get { return fTrailer2Registration; }
            set { SetPropertyValue<string>(nameof(Trailer2Registration), ref fTrailer2Registration, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"ExpectedTrucksReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        double fOriginTarWeight;
        public double OriginTarWeight
        {
            get { return fOriginTarWeight; }
            set { SetPropertyValue<double>(nameof(OriginTarWeight), ref fOriginTarWeight, value); }
        }
        string fOriginWeighbridgeTicketNo;
        [Size(50)]
        public string OriginWeighbridgeTicketNo
        {
            get { return fOriginWeighbridgeTicketNo; }
            set { SetPropertyValue<string>(nameof(OriginWeighbridgeTicketNo), ref fOriginWeighbridgeTicketNo, value); }
        }
        double fOriginNettWeight;
        public double OriginNettWeight
        {
            get { return fOriginNettWeight; }
            set { SetPropertyValue<double>(nameof(OriginNettWeight), ref fOriginNettWeight, value); }
        }
        string fLotNumber;
        [Size(50)]
        public string LotNumber
        {
            get { return fLotNumber; }
            set { SetPropertyValue<string>(nameof(LotNumber), ref fLotNumber, value); }
        }
        string fBillOfEntry;
        [Size(50)]
        public string BillOfEntry
        {
            get { return fBillOfEntry; }
            set { SetPropertyValue<string>(nameof(BillOfEntry), ref fBillOfEntry, value); }
        }
        double fOriginGrossWeight;
        public double OriginGrossWeight
        {
            get { return fOriginGrossWeight; }
            set { SetPropertyValue<double>(nameof(OriginGrossWeight), ref fOriginGrossWeight, value); }
        }
        DateTime fDateDispatched;
        public DateTime DateDispatched
        {
            get { return fDateDispatched; }
            set { SetPropertyValue<DateTime>(nameof(DateDispatched), ref fDateDispatched, value); }
        }
        DateTime fDateWeighed;
        public DateTime DateWeighed
        {
            get { return fDateWeighed; }
            set { SetPropertyValue<DateTime>(nameof(DateWeighed), ref fDateWeighed, value); }
        }
        DateTime fPlannedArrivalDate;
        public DateTime PlannedArrivalDate
        {
            get { return fPlannedArrivalDate; }
            set { SetPropertyValue<DateTime>(nameof(PlannedArrivalDate), ref fPlannedArrivalDate, value); }
        }
        DateTime fActualArrivalDate;
        public DateTime ActualArrivalDate
        {
            get { return fActualArrivalDate; }
            set { SetPropertyValue<DateTime>(nameof(ActualArrivalDate), ref fActualArrivalDate, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        [Association(@"Product_ProductReceiveReferencesExpectedTrucks")]
        public XPCollection<Product_ProductReceive> Product_ProductReceives { get { return GetCollection<Product_ProductReceive>(nameof(Product_ProductReceives)); } }
    }

}
