//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class ExpectedProductItem : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fBarcode;
        [Size(50)]
        public string Barcode
        {
            get { return fBarcode; }
            set { SetPropertyValue<string>(nameof(Barcode), ref fBarcode, value); }
        }
        int fQuantity;
        public int Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<int>(nameof(Quantity), ref fQuantity, value); }
        }
        double fItemOriginGross;
        public double ItemOriginGross
        {
            get { return fItemOriginGross; }
            set { SetPropertyValue<double>(nameof(ItemOriginGross), ref fItemOriginGross, value); }
        }
        double fItemOriginNett;
        public double ItemOriginNett
        {
            get { return fItemOriginNett; }
            set { SetPropertyValue<double>(nameof(ItemOriginNett), ref fItemOriginNett, value); }
        }
        string fLotNumber;
        [Size(50)]
        public string LotNumber
        {
            get { return fLotNumber; }
            set { SetPropertyValue<string>(nameof(LotNumber), ref fLotNumber, value); }
        }
    }

}
