//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class FileData : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        int fsize;
        public int size
        {
            get { return fsize; }
            set { SetPropertyValue<int>(nameof(size), ref fsize, value); }
        }
        string fFileName;
        [Size(260)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>(nameof(FileName), ref fFileName, value); }
        }
        byte[] fContent;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Content
        {
            get { return fContent; }
            set { SetPropertyValue<byte[]>(nameof(Content), ref fContent, value); }
        }
        [Association(@"Document_OrdersReferencesFileData")]
        public XPCollection<Document_Orders> Document_Orderss { get { return GetCollection<Document_Orders>(nameof(Document_Orderss)); } }
        //[Association(@"Order_OrderOutReferencesFileData")]
        //public XPCollection<Order_OrderOut> Order_OrderOuts { get { return GetCollection<Order_OrderOut>(nameof(Order_OrderOuts)); } }
        //[Association(@"Order_OrderOutReferencesFileData1")]
        //public XPCollection<Order_OrderOut> Order_OrderOuts1 { get { return GetCollection<Order_OrderOut>(nameof(Order_OrderOuts1)); } }
        [Association(@"Template_DocumentReferencesFileData")]
        public XPCollection<Template_Document> Template_Documents { get { return GetCollection<Template_Document>(nameof(Template_Documents)); } }
    }

}
