//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class HatchScan : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fTruckScan;
        [Size(150)]
        public string TruckScan
        {
            get { return fTruckScan; }
            set { SetPropertyValue<string>(nameof(TruckScan), ref fTruckScan, value); }
        }
        Order_VesselHatch fOrderVesselHatchID;
        [Association(@"HatchScanReferencesOrder_VesselHatch")]
        public Order_VesselHatch OrderVesselHatchID
        {
            get { return fOrderVesselHatchID; }
            set { SetPropertyValue<Order_VesselHatch>(nameof(OrderVesselHatchID), ref fOrderVesselHatchID, value); }
        }
        DateTime fScanDate;
        public DateTime ScanDate
        {
            get { return fScanDate; }
            set { SetPropertyValue<DateTime>(nameof(ScanDate), ref fScanDate, value); }
        }
        string fTruckReg;
        [Size(30)]
        public string TruckReg
        {
            get { return fTruckReg; }
            set { SetPropertyValue<string>(nameof(TruckReg), ref fTruckReg, value); }
        }
    }

}
