//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Incident : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fOrderReference;
        [Size(50)]
        public string OrderReference
        {
            get { return fOrderReference; }
            set { SetPropertyValue<string>(nameof(OrderReference), ref fOrderReference, value); }
        }
        Library_IncidentType fIncidentTypeID;
        [Association(@"IncidentReferencesLibrary_IncidentType")]
        public Library_IncidentType IncidentTypeID
        {
            get { return fIncidentTypeID; }
            set { SetPropertyValue<Library_IncidentType>(nameof(IncidentTypeID), ref fIncidentTypeID, value); }
        }
        Library_IncidentCause fIncidentCauseID;
        [Association(@"IncidentReferencesLibrary_IncidentCause")]
        public Library_IncidentCause IncidentCauseID
        {
            get { return fIncidentCauseID; }
            set { SetPropertyValue<Library_IncidentCause>(nameof(IncidentCauseID), ref fIncidentCauseID, value); }
        }
        DateTime fDateOccurred;
        public DateTime DateOccurred
        {
            get { return fDateOccurred; }
            set { SetPropertyValue<DateTime>(nameof(DateOccurred), ref fDateOccurred, value); }
        }
        string fComment;
        [Size(300)]
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        byte[] fIncidentPhoto1;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] IncidentPhoto1
        {
            get { return fIncidentPhoto1; }
            set { SetPropertyValue<byte[]>(nameof(IncidentPhoto1), ref fIncidentPhoto1, value); }
        }
        byte[] fIncidentPhoto2;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] IncidentPhoto2
        {
            get { return fIncidentPhoto2; }
            set { SetPropertyValue<byte[]>(nameof(IncidentPhoto2), ref fIncidentPhoto2, value); }
        }
        byte[] fIncidentPhoto3;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] IncidentPhoto3
        {
            get { return fIncidentPhoto3; }
            set { SetPropertyValue<byte[]>(nameof(IncidentPhoto3), ref fIncidentPhoto3, value); }
        }
    }

}
