//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class KpiHistoryItem : XPBaseObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        KpiInstance fKpiInstance;
        [Association(@"KpiHistoryItemReferencesKpiInstance")]
        public KpiInstance KpiInstance
        {
            get { return fKpiInstance; }
            set { SetPropertyValue<KpiInstance>(nameof(KpiInstance), ref fKpiInstance, value); }
        }
        DateTime fRangeStart;
        public DateTime RangeStart
        {
            get { return fRangeStart; }
            set { SetPropertyValue<DateTime>(nameof(RangeStart), ref fRangeStart, value); }
        }
        DateTime fRangeEnd;
        public DateTime RangeEnd
        {
            get { return fRangeEnd; }
            set { SetPropertyValue<DateTime>(nameof(RangeEnd), ref fRangeEnd, value); }
        }
        double fValue;
        public double Value
        {
            get { return fValue; }
            set { SetPropertyValue<double>(nameof(Value), ref fValue, value); }
        }
    }

}
