//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class KpiScorecardScorecards_KpiInstanceIndicators : XPBaseObject
    {
        KpiInstance fIndicators;
        [Indexed(@"Scorecards", Name = @"iIndicatorsScorecards_KpiScorecardScorecards_KpiInstanceIndicators", Unique = true)]
        [Association(@"KpiScorecardScorecards_KpiInstanceIndicatorsReferencesKpiInstance")]
        public KpiInstance Indicators
        {
            get { return fIndicators; }
            set { SetPropertyValue<KpiInstance>(nameof(Indicators), ref fIndicators, value); }
        }
        KpiScorecard fScorecards;
        [Association(@"KpiScorecardScorecards_KpiInstanceIndicatorsReferencesKpiScorecard")]
        public KpiScorecard Scorecards
        {
            get { return fScorecards; }
            set { SetPropertyValue<KpiScorecard>(nameof(Scorecards), ref fScorecards, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
