//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_Site : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Library_RCMClient fRCMClientID;
        [Association(@"Library_SiteReferencesLibrary_RCMClient")]
        public Library_RCMClient RCMClientID
        {
            get { return fRCMClientID; }
            set { SetPropertyValue<Library_RCMClient>(nameof(RCMClientID), ref fRCMClientID, value); }
        }
        string fHeaderSecondLine;
        [Size(50)]
        public string HeaderSecondLine
        {
            get { return fHeaderSecondLine; }
            set { SetPropertyValue<string>(nameof(HeaderSecondLine), ref fHeaderSecondLine, value); }
        }
        string fHeaderThirdLine;
        public string HeaderThirdLine
        {
            get { return fHeaderThirdLine; }
            set { SetPropertyValue<string>(nameof(HeaderThirdLine), ref fHeaderThirdLine, value); }
        }
        string fHeaderFourthLine;
        public string HeaderFourthLine
        {
            get { return fHeaderFourthLine; }
            set { SetPropertyValue<string>(nameof(HeaderFourthLine), ref fHeaderFourthLine, value); }
        }
        string fHeaderFithLine;
        public string HeaderFithLine
        {
            get { return fHeaderFithLine; }
            set { SetPropertyValue<string>(nameof(HeaderFithLine), ref fHeaderFithLine, value); }
        }
        string fFACNumber;
        public string FACNumber
        {
            get { return fFACNumber; }
            set { SetPropertyValue<string>(nameof(FACNumber), ref fFACNumber, value); }
        }
        byte[] fLogo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<byte[]>(nameof(Logo), ref fLogo, value); }
        }
        int fTruckReserveTonnage;
        public int TruckReserveTonnage
        {
            get { return fTruckReserveTonnage; }
            set { SetPropertyValue<int>(nameof(TruckReserveTonnage), ref fTruckReserveTonnage, value); }
        }
        [Association(@"BookingReference_ProductDispatchReferencesLibrary_Site")]
        public XPCollection<BookingReference_ProductDispatch> BookingReference_ProductDispatchs { get { return GetCollection<BookingReference_ProductDispatch>(nameof(BookingReference_ProductDispatchs)); } }
        [Association(@"Container_EmptyInReferencesLibrary_Site")]
        public XPCollection<Container_EmptyIn> Container_EmptyIns { get { return GetCollection<Container_EmptyIn>(nameof(Container_EmptyIns)); } }
        [Association(@"Container_EmptyOutReferencesLibrary_Site")]
        public XPCollection<Container_EmptyOut> Container_EmptyOuts { get { return GetCollection<Container_EmptyOut>(nameof(Container_EmptyOuts)); } }
        [Association(@"Container_FullInReferencesLibrary_Site")]
        public XPCollection<Container_FullIn> Container_FullIns { get { return GetCollection<Container_FullIn>(nameof(Container_FullIns)); } }
        [Association(@"Container_FullOutReferencesLibrary_Site")]
        public XPCollection<Container_FullOut> Container_FullOuts { get { return GetCollection<Container_FullOut>(nameof(Container_FullOuts)); } }
        [Association(@"Container_PackedReferencesLibrary_Site")]
        public XPCollection<Container_Packed> Container_Packeds { get { return GetCollection<Container_Packed>(nameof(Container_Packeds)); } }
        [Association(@"Order_OrderInReferencesLibrary_Site")]
        public XPCollection<Order_OrderIn> Order_OrderIns { get { return GetCollection<Order_OrderIn>(nameof(Order_OrderIns)); } }
        [Association(@"Product_ProductDispatchReferencesLibrary_Site")]
        public XPCollection<Product_ProductDispatch> Product_ProductDispatchs { get { return GetCollection<Product_ProductDispatch>(nameof(Product_ProductDispatchs)); } }
        [Association(@"Product_ProductReceiveReferencesLibrary_Site")]
        public XPCollection<Product_ProductReceive> Product_ProductReceives { get { return GetCollection<Product_ProductReceive>(nameof(Product_ProductReceives)); } }
        [Association(@"Product_Receive_RailReferencesLibrary_Site")]
        public XPCollection<Product_Receive_Rail> Product_Receive_Rails { get { return GetCollection<Product_Receive_Rail>(nameof(Product_Receive_Rails)); } }
    }

}
