//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_ProductType : XPLiteObject
    {
        int fID;
        [Key]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(300)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Library_UnitOfMeasure fUnitOfMeasureID;
        [Association(@"Library_ProductTypeReferencesLibrary_UnitOfMeasure")]
        public Library_UnitOfMeasure UnitOfMeasureID
        {
            get { return fUnitOfMeasureID; }
            set { SetPropertyValue<Library_UnitOfMeasure>(nameof(UnitOfMeasureID), ref fUnitOfMeasureID, value); }
        }
        [Association(@"Library_ProductReferencesLibrary_ProductType")]
        public XPCollection<Library_Product> Library_Products { get { return GetCollection<Library_Product>(nameof(Library_Products)); } }
    }

}
