//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_UnitOfMeasure : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(300)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fUnitOfMeasureShortCode;
        [Size(10)]
        public string UnitOfMeasureShortCode
        {
            get { return fUnitOfMeasureShortCode; }
            set { SetPropertyValue<string>(nameof(UnitOfMeasureShortCode), ref fUnitOfMeasureShortCode, value); }
        }
        [Association(@"Library_PackagingReferencesLibrary_UnitOfMeasure")]
        public XPCollection<Library_Packaging> Library_Packagings { get { return GetCollection<Library_Packaging>(nameof(Library_Packagings)); } }
        [Association(@"Library_ProductTypeReferencesLibrary_UnitOfMeasure")]
        public XPCollection<Library_ProductType> Library_ProductTypes { get { return GetCollection<Library_ProductType>(nameof(Library_ProductTypes)); } }
    }

}
