//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_Product : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(300)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fProductShortCode;
        [Size(10)]
        public string ProductShortCode
        {
            get { return fProductShortCode; }
            set { SetPropertyValue<string>(nameof(ProductShortCode), ref fProductShortCode, value); }
        }
        Library_ProductType fProductTypeID;
        [Association(@"Library_ProductReferencesLibrary_ProductType")]
        public Library_ProductType ProductTypeID
        {
            get { return fProductTypeID; }
            set { SetPropertyValue<Library_ProductType>(nameof(ProductTypeID), ref fProductTypeID, value); }
        }
        [Association(@"Order_OrderInReferencesLibrary_Product")]
        public XPCollection<Order_OrderIn> Order_OrderIns { get { return GetCollection<Order_OrderIn>(nameof(Order_OrderIns)); } }
        [Association(@"Order_OrderOutReferencesLibrary_Product")]
        public XPCollection<Order_OrderOut> Order_OrderOuts { get { return GetCollection<Order_OrderOut>(nameof(Order_OrderOuts)); } }
        [Association(@"Order_VesselHatchReferencesLibrary_Product")]
        public XPCollection<Order_VesselHatch> Order_VesselHatchs { get { return GetCollection<Order_VesselHatch>(nameof(Order_VesselHatchs)); } }
    }

}
