//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_ContainerSize : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(300)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        double fMinWeight;
        public double MinWeight
        {
            get { return fMinWeight; }
            set { SetPropertyValue<double>(nameof(MinWeight), ref fMinWeight, value); }
        }
        double fMaxweight;
        public double Maxweight
        {
            get { return fMaxweight; }
            set { SetPropertyValue<double>(nameof(Maxweight), ref fMaxweight, value); }
        }
        string fContainerSizeShortCode;
        [Size(10)]
        public string ContainerSizeShortCode
        {
            get { return fContainerSizeShortCode; }
            set { SetPropertyValue<string>(nameof(ContainerSizeShortCode), ref fContainerSizeShortCode, value); }
        }
        [Association(@"ContainerReferencesLibrary_ContainerSize")]
        public XPCollection<Container> Containers { get { return GetCollection<Container>(nameof(Containers)); } }
        [Association(@"Product_Receive_RailReferencesLibrary_ContainerSize")]
        public XPCollection<Product_Receive_Rail> Product_Receive_Rails { get { return GetCollection<Product_Receive_Rail>(nameof(Product_Receive_Rails)); } }
    }

}
