//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_CargoType : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"AccessControlReferencesLibrary_CargoType")]
        public XPCollection<AccessControl> AccessControls { get { return GetCollection<AccessControl>(nameof(AccessControls)); } }
        [Association(@"AccessControlExitReferencesLibrary_CargoType")]
        public XPCollection<AccessControlExit> AccessControlExits { get { return GetCollection<AccessControlExit>(nameof(AccessControlExits)); } }
    }

}
