//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_RCMClient : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(300)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fKeyContactName;
        [Size(50)]
        public string KeyContactName
        {
            get { return fKeyContactName; }
            set { SetPropertyValue<string>(nameof(KeyContactName), ref fKeyContactName, value); }
        }
        string fKeyContactTelephone;
        [Size(50)]
        public string KeyContactTelephone
        {
            get { return fKeyContactTelephone; }
            set { SetPropertyValue<string>(nameof(KeyContactTelephone), ref fKeyContactTelephone, value); }
        }
        [Association(@"Library_SiteReferencesLibrary_RCMClient")]
        public XPCollection<Library_Site> Library_Sites { get { return GetCollection<Library_Site>(nameof(Library_Sites)); } }
    }

}
