//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_DocumentCategory : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fCategoryName;
        [Size(50)]
        public string CategoryName
        {
            get { return fCategoryName; }
            set { SetPropertyValue<string>(nameof(CategoryName), ref fCategoryName, value); }
        }
        [Association(@"Document_BookingReferenceReferencesLibrary_DocumentCategory")]
        public XPCollection<Document_BookingReference> Document_BookingReferences { get { return GetCollection<Document_BookingReference>(nameof(Document_BookingReferences)); } }
        [Association(@"Document_OrdersReferencesLibrary_DocumentCategory")]
        public XPCollection<Document_Orders> Document_Orderss { get { return GetCollection<Document_Orders>(nameof(Document_Orderss)); } }
        [Association(@"Template_DocumentReferencesLibrary_DocumentCategory")]
        public XPCollection<Template_Document> Template_Documents { get { return GetCollection<Template_Document>(nameof(Template_Documents)); } }
    }

}
