//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Library_Grade : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fShortCode;
        [Size(50)]
        public string ShortCode
        {
            get { return fShortCode; }
            set { SetPropertyValue<string>(nameof(ShortCode), ref fShortCode, value); }
        }
        [Association(@"Container_PackedReferencesLibrary_Grade")]
        public XPCollection<Container_Packed> Container_Packeds { get { return GetCollection<Container_Packed>(nameof(Container_Packeds)); } }
        [Association(@"Product_ProductItemReferencesLibrary_Grade")]
        public XPCollection<Product_ProductItem> Product_ProductItems { get { return GetCollection<Product_ProductItem>(nameof(Product_ProductItems)); } }
        [Association(@"Product_ProductReceiveReferencesLibrary_Grade")]
        public XPCollection<Product_ProductReceive> Product_ProductReceives { get { return GetCollection<Product_ProductReceive>(nameof(Product_ProductReceives)); } }
        [Association(@"Product_ReceiveCountReferencesLibrary_Grade")]
        public XPCollection<Product_ReceiveCount> Product_ReceiveCounts { get { return GetCollection<Product_ReceiveCount>(nameof(Product_ReceiveCounts)); } }
    }

}
