//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class ModelDifference : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fUserId;
        public string UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<string>(nameof(UserId), ref fUserId, value); }
        }
        string fContextId;
        public string ContextId
        {
            get { return fContextId; }
            set { SetPropertyValue<string>(nameof(ContextId), ref fContextId, value); }
        }
        int fVersion;
        public int Version
        {
            get { return fVersion; }
            set { SetPropertyValue<int>(nameof(Version), ref fVersion, value); }
        }
        [Association(@"ModelDifferenceAspectReferencesModelDifference")]
        public XPCollection<ModelDifferenceAspect> ModelDifferenceAspects { get { return GetCollection<ModelDifferenceAspect>(nameof(ModelDifferenceAspects)); } }
    }

}
