//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class ModelDifferenceAspect : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fXml;
        [Size(SizeAttribute.Unlimited)]
        public string Xml
        {
            get { return fXml; }
            set { SetPropertyValue<string>(nameof(Xml), ref fXml, value); }
        }
        ModelDifference fOwner;
        [Association(@"ModelDifferenceAspectReferencesModelDifference")]
        public ModelDifference Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<ModelDifference>(nameof(Owner), ref fOwner, value); }
        }
    }

}
