//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Order_OrderIn : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Library_Client fOrderInClientID;
        [Association(@"Order_OrderInReferencesLibrary_Client")]
        public Library_Client OrderInClientID
        {
            get { return fOrderInClientID; }
            set { SetPropertyValue<Library_Client>(nameof(OrderInClientID), ref fOrderInClientID, value); }
        }
        string fOrderNo;
        [Size(50)]
        public string OrderNo
        {
            get { return fOrderNo; }
            set { SetPropertyValue<string>(nameof(OrderNo), ref fOrderNo, value); }
        }
        string fContractID;
        [Size(50)]
        public string ContractID
        {
            get { return fContractID; }
            set { SetPropertyValue<string>(nameof(ContractID), ref fContractID, value); }
        }
        string fRecDescription;
        public string RecDescription
        {
            get { return fRecDescription; }
            set { SetPropertyValue<string>(nameof(RecDescription), ref fRecDescription, value); }
        }
        string fClientReferenceNo;
        [Size(50)]
        public string ClientReferenceNo
        {
            get { return fClientReferenceNo; }
            set { SetPropertyValue<string>(nameof(ClientReferenceNo), ref fClientReferenceNo, value); }
        }
        Library_Product fProductID;
        [Association(@"Order_OrderInReferencesLibrary_Product")]
        public Library_Product ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<Library_Product>(nameof(ProductID), ref fProductID, value); }
        }
        Library_Packaging fPackagingID;
        [Association(@"Order_OrderInReferencesLibrary_Packaging")]
        public Library_Packaging PackagingID
        {
            get { return fPackagingID; }
            set { SetPropertyValue<Library_Packaging>(nameof(PackagingID), ref fPackagingID, value); }
        }
        double fQuantity;
        public double Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<double>(nameof(Quantity), ref fQuantity, value); }
        }
        int fAmtBookedContainers;
        public int AmtBookedContainers
        {
            get { return fAmtBookedContainers; }
            set { SetPropertyValue<int>(nameof(AmtBookedContainers), ref fAmtBookedContainers, value); }
        }
        DateTime fPlannedStartReveiveDate;
        public DateTime PlannedStartReveiveDate
        {
            get { return fPlannedStartReveiveDate; }
            set { SetPropertyValue<DateTime>(nameof(PlannedStartReveiveDate), ref fPlannedStartReveiveDate, value); }
        }
        Library_OriginType fOriginTypeID;
        [Association(@"Order_OrderInReferencesLibrary_OriginType")]
        public Library_OriginType OriginTypeID
        {
            get { return fOriginTypeID; }
            set { SetPropertyValue<Library_OriginType>(nameof(OriginTypeID), ref fOriginTypeID, value); }
        }
        Library_OrderType fOrderTypeID;
        [Association(@"Order_OrderInReferencesLibrary_OrderType")]
        public Library_OrderType OrderTypeID
        {
            get { return fOrderTypeID; }
            set { SetPropertyValue<Library_OrderType>(nameof(OrderTypeID), ref fOrderTypeID, value); }
        }
        DateTime fOrderDate;
        public DateTime OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref fOrderDate, value); }
        }
        Order_VesselIntake fVesselIntakeID;
        [Association(@"Order_OrderInReferencesOrder_VesselIntake")]
        public Order_VesselIntake VesselIntakeID
        {
            get { return fVesselIntakeID; }
            set { SetPropertyValue<Order_VesselIntake>(nameof(VesselIntakeID), ref fVesselIntakeID, value); }
        }
        bool fStatus;
        public bool Status
        {
            get { return fStatus; }
            set { SetPropertyValue<bool>(nameof(Status), ref fStatus, value); }
        }
        bool fRequireSchedule;
        public bool RequireSchedule
        {
            get { return fRequireSchedule; }
            set { SetPropertyValue<bool>(nameof(RequireSchedule), ref fRequireSchedule, value); }
        }
        string fOriginName;
        [Size(50)]
        public string OriginName
        {
            get { return fOriginName; }
            set { SetPropertyValue<string>(nameof(OriginName), ref fOriginName, value); }
        }
        Library_Sampler fSamplerID;
        [Association(@"Order_OrderInReferencesLibrary_Sampler")]
        public Library_Sampler SamplerID
        {
            get { return fSamplerID; }
            set { SetPropertyValue<Library_Sampler>(nameof(SamplerID), ref fSamplerID, value); }
        }
        Library_Site fSiteID;
        [Association(@"Order_OrderInReferencesLibrary_Site")]
        public Library_Site SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<Library_Site>(nameof(SiteID), ref fSiteID, value); }
        }
        int fNumberLoads;
        public int NumberLoads
        {
            get { return fNumberLoads; }
            set { SetPropertyValue<int>(nameof(NumberLoads), ref fNumberLoads, value); }
        }
        bool fUseProductItems;
        public bool UseProductItems
        {
            get { return fUseProductItems; }
            set { SetPropertyValue<bool>(nameof(UseProductItems), ref fUseProductItems, value); }
        }
        [Association(@"Document_OrdersReferencesOrder_OrderIn")]
        public XPCollection<Document_Orders> Document_Orderss { get { return GetCollection<Document_Orders>(nameof(Document_Orderss)); } }
        [Association(@"Order_BookingReferenceReferencesOrder_OrderIn")]
        public XPCollection<Order_BookingReference> Order_BookingReferences { get { return GetCollection<Order_BookingReference>(nameof(Order_BookingReferences)); } }
        [Association(@"Order_OrderOutReferencesOrder_OrderIn")]
        public XPCollection<Order_OrderOut> Order_OrderOuts { get { return GetCollection<Order_OrderOut>(nameof(Order_OrderOuts)); } }
        [Association(@"Order_VesselHatchReferencesOrder_OrderIn")]
        public XPCollection<Order_VesselHatch> Order_VesselHatchs { get { return GetCollection<Order_VesselHatch>(nameof(Order_VesselHatchs)); } }
        [Association(@"Product_Dispatch_RailReferencesOrder_OrderIn")]
        public XPCollection<Product_Dispatch_Rail> Product_Dispatch_Rails { get { return GetCollection<Product_Dispatch_Rail>(nameof(Product_Dispatch_Rails)); } }
        [Association(@"Product_ProductDispatchReferencesOrder_OrderIn")]
        public XPCollection<Product_ProductDispatch> Product_ProductDispatchs { get { return GetCollection<Product_ProductDispatch>(nameof(Product_ProductDispatchs)); } }
        [Association(@"Product_ProductReceiveReferencesOrder_OrderIn")]
        public XPCollection<Product_ProductReceive> Product_ProductReceives { get { return GetCollection<Product_ProductReceive>(nameof(Product_ProductReceives)); } }
        [Association(@"Product_Receive_RailReferencesOrder_OrderIn")]
        public XPCollection<Product_Receive_Rail> Product_Receive_Rails { get { return GetCollection<Product_Receive_Rail>(nameof(Product_Receive_Rails)); } }
        [Association(@"WagonConsignmentReferencesOrder_OrderIn")]
        public XPCollection<WagonConsignment> WagonConsignments { get { return GetCollection<WagonConsignment>(nameof(WagonConsignments)); } }
    }

}
