//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Order_VesselIntake : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fJobCardNo;
        [Size(50)]
        public string JobCardNo
        {
            get { return fJobCardNo; }
            set { SetPropertyValue<string>(nameof(JobCardNo), ref fJobCardNo, value); }
        }
        string fVoyageNo;
        [Size(50)]
        public string VoyageNo
        {
            get { return fVoyageNo; }
            set { SetPropertyValue<string>(nameof(VoyageNo), ref fVoyageNo, value); }
        }
        Library_Vessel fVesselID;
        [Association(@"Order_VesselIntakeReferencesLibrary_Vessel")]
        public Library_Vessel VesselID
        {
            get { return fVesselID; }
            set { SetPropertyValue<Library_Vessel>(nameof(VesselID), ref fVesselID, value); }
        }
        Library_HandlingPoint fHandlingPointID;
        [Association(@"Order_VesselIntakeReferencesLibrary_HandlingPoint")]
        public Library_HandlingPoint HandlingPointID
        {
            get { return fHandlingPointID; }
            set { SetPropertyValue<Library_HandlingPoint>(nameof(HandlingPointID), ref fHandlingPointID, value); }
        }
        Library_Charterer fChartererID;
        [Association(@"Order_VesselIntakeReferencesLibrary_Charterer")]
        public Library_Charterer ChartererID
        {
            get { return fChartererID; }
            set { SetPropertyValue<Library_Charterer>(nameof(ChartererID), ref fChartererID, value); }
        }
        Library_ShippingAgent fShippingAgentID;
        [Association(@"Order_VesselIntakeReferencesLibrary_ShippingAgent")]
        public Library_ShippingAgent ShippingAgentID
        {
            get { return fShippingAgentID; }
            set { SetPropertyValue<Library_ShippingAgent>(nameof(ShippingAgentID), ref fShippingAgentID, value); }
        }
        bool fEnableHatchScan;
        public bool EnableHatchScan
        {
            get { return fEnableHatchScan; }
            set { SetPropertyValue<bool>(nameof(EnableHatchScan), ref fEnableHatchScan, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>(nameof(BirthDate), ref fBirthDate, value); }
        }
        DateTime fCommencementDate;
        public DateTime CommencementDate
        {
            get { return fCommencementDate; }
            set { SetPropertyValue<DateTime>(nameof(CommencementDate), ref fCommencementDate, value); }
        }
        DateTime fCompletionDate;
        public DateTime CompletionDate
        {
            get { return fCompletionDate; }
            set { SetPropertyValue<DateTime>(nameof(CompletionDate), ref fCompletionDate, value); }
        }
        DateTime fFinalizedDate;
        public DateTime FinalizedDate
        {
            get { return fFinalizedDate; }
            set { SetPropertyValue<DateTime>(nameof(FinalizedDate), ref fFinalizedDate, value); }
        }
        double fAmount;
        public double Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<double>(nameof(Amount), ref fAmount, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        bool fStatus;
        public bool Status
        {
            get { return fStatus; }
            set { SetPropertyValue<bool>(nameof(Status), ref fStatus, value); }
        }
        [Association(@"Order_OrderInReferencesOrder_VesselIntake")]
        public XPCollection<Order_OrderIn> Order_OrderIns { get { return GetCollection<Order_OrderIn>(nameof(Order_OrderIns)); } }
        [Association(@"Order_VesselHatchReferencesOrder_VesselIntake")]
        public XPCollection<Order_VesselHatch> Order_VesselHatchs { get { return GetCollection<Order_VesselHatch>(nameof(Order_VesselHatchs)); } }
    }

}
