//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Order_VesselHatch : XPLiteObject
    {
        string ffHatchLookupDisplayText;
        public string fHatchLookupDisplayText
        {
            get { return ffHatchLookupDisplayText; }
            set { SetPropertyValue<string>(nameof(fHatchLookupDisplayText), ref ffHatchLookupDisplayText, value); }
        }
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        int fHatchNo;
        public int HatchNo
        {
            get { return fHatchNo; }
            set { SetPropertyValue<int>(nameof(HatchNo), ref fHatchNo, value); }
        }
        int fHatchDescription;
        public int HatchDescription
        {
            get { return fHatchDescription; }
            set { SetPropertyValue<int>(nameof(HatchDescription), ref fHatchDescription, value); }
        }
        Library_Product fProductID;
        [Association(@"Order_VesselHatchReferencesLibrary_Product")]
        public Library_Product ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<Library_Product>(nameof(ProductID), ref fProductID, value); }
        }
        Order_VesselIntake fOrderVesselIntakeID;
        [Association(@"Order_VesselHatchReferencesOrder_VesselIntake")]
        public Order_VesselIntake OrderVesselIntakeID
        {
            get { return fOrderVesselIntakeID; }
            set { SetPropertyValue<Order_VesselIntake>(nameof(OrderVesselIntakeID), ref fOrderVesselIntakeID, value); }
        }
        Order_OrderIn fOrderID;
        [Association(@"Order_VesselHatchReferencesOrder_OrderIn")]
        public Order_OrderIn OrderID
        {
            get { return fOrderID; }
            set { SetPropertyValue<Order_OrderIn>(nameof(OrderID), ref fOrderID, value); }
        }
        double fAmount;
        public double Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<double>(nameof(Amount), ref fAmount, value); }
        }
        Order_OrderOut fOrderOrderOutID;
        [Association(@"Order_VesselHatchReferencesOrder_OrderOut")]
        public Order_OrderOut OrderOrderOutID
        {
            get { return fOrderOrderOutID; }
            set { SetPropertyValue<Order_OrderOut>(nameof(OrderOrderOutID), ref fOrderOrderOutID, value); }
        }
        [Association(@"HatchScanReferencesOrder_VesselHatch")]
        public XPCollection<HatchScan> HatchScans { get { return GetCollection<HatchScan>(nameof(HatchScans)); } }
        [Association(@"Product_ProductDispatchReferencesOrder_VesselHatch")]
        public XPCollection<Product_ProductDispatch> Product_ProductDispatchs { get { return GetCollection<Product_ProductDispatch>(nameof(Product_ProductDispatchs)); } }
        [Association(@"Product_ProductReceiveReferencesOrder_VesselHatch")]
        public XPCollection<Product_ProductReceive> Product_ProductReceives { get { return GetCollection<Product_ProductReceive>(nameof(Product_ProductReceives)); } }
        [Association(@"Product_Receive_RailReferencesOrder_VesselHatch")]
        public XPCollection<Product_Receive_Rail> Product_Receive_Rails { get { return GetCollection<Product_Receive_Rail>(nameof(Product_Receive_Rails)); } }
    }

}
