//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Order_OrderOut : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Library_Client fOrderInClientID;
        [Association(@"Order_OrderOutReferencesLibrary_Client")]
        public Library_Client OrderInClientID
        {
            get { return fOrderInClientID; }
            set { SetPropertyValue<Library_Client>(nameof(OrderInClientID), ref fOrderInClientID, value); }
        }
        string fReleaseOrderNo;
        [Size(50)]
        public string ReleaseOrderNo
        {
            get { return fReleaseOrderNo; }
            set { SetPropertyValue<string>(nameof(ReleaseOrderNo), ref fReleaseOrderNo, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fClientReferenceNo;
        [Size(50)]
        public string ClientReferenceNo
        {
            get { return fClientReferenceNo; }
            set { SetPropertyValue<string>(nameof(ClientReferenceNo), ref fClientReferenceNo, value); }
        }
        Library_Product fProductID;
        [Association(@"Order_OrderOutReferencesLibrary_Product")]
        public Library_Product ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<Library_Product>(nameof(ProductID), ref fProductID, value); }
        }
        int fPackagingID;
        public int PackagingID
        {
            get { return fPackagingID; }
            set { SetPropertyValue<int>(nameof(PackagingID), ref fPackagingID, value); }
        }
        double fQuantity;
        public double Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<double>(nameof(Quantity), ref fQuantity, value); }
        }
        int fAmtBookedContainers;
        public int AmtBookedContainers
        {
            get { return fAmtBookedContainers; }
            set { SetPropertyValue<int>(nameof(AmtBookedContainers), ref fAmtBookedContainers, value); }
        }
        DateTime fPlannedStartDispatchDate;
        public DateTime PlannedStartDispatchDate
        {
            get { return fPlannedStartDispatchDate; }
            set { SetPropertyValue<DateTime>(nameof(PlannedStartDispatchDate), ref fPlannedStartDispatchDate, value); }
        }
        int fDestinationTypeID;
        public int DestinationTypeID
        {
            get { return fDestinationTypeID; }
            set { SetPropertyValue<int>(nameof(DestinationTypeID), ref fDestinationTypeID, value); }
        }
        int fOrderTypeID;
        public int OrderTypeID
        {
            get { return fOrderTypeID; }
            set { SetPropertyValue<int>(nameof(OrderTypeID), ref fOrderTypeID, value); }
        }
        DateTime fOrderDate;
        public DateTime OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref fOrderDate, value); }
        }
        bool fStatus;
        public bool Status
        {
            get { return fStatus; }
            set { SetPropertyValue<bool>(nameof(Status), ref fStatus, value); }
        }
        string fDestinationName;
        [Size(50)]
        public string DestinationName
        {
            get { return fDestinationName; }
            set { SetPropertyValue<string>(nameof(DestinationName), ref fDestinationName, value); }
        }
        int fSamplerID;
        public int SamplerID
        {
            get { return fSamplerID; }
            set { SetPropertyValue<int>(nameof(SamplerID), ref fSamplerID, value); }
        }
        int fSiteID;
        public int SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<int>(nameof(SiteID), ref fSiteID, value); }
        }
        Order_OrderIn fRecOrderID;
        [Association(@"Order_OrderOutReferencesOrder_OrderIn")]
        public Order_OrderIn RecOrderID
        {
            get { return fRecOrderID; }
            set { SetPropertyValue<Order_OrderIn>(nameof(RecOrderID), ref fRecOrderID, value); }
        }
        //FileData fDocument1;
        //[Association(@"Order_OrderOutReferencesFileData")]
        //public FileData Document1
        //{
        //    get { return fDocument1; }
        //    set { SetPropertyValue<FileData>(nameof(Document1), ref fDocument1, value); }
        //}
        [Association(@"Order_VesselHatchReferencesOrder_OrderOut")]
        public XPCollection<Order_VesselHatch> Order_VesselHatchs { get { return GetCollection<Order_VesselHatch>(nameof(Order_VesselHatchs)); } }
        [Association(@"Product_ProductDispatchReferencesOrder_OrderOut")]
        public XPCollection<Product_ProductDispatch> Product_ProductDispatchs { get { return GetCollection<Product_ProductDispatch>(nameof(Product_ProductDispatchs)); } }
    }

}
