//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class PermissionPolicyUserUsers_PermissionPolicyRoleRoles : XPBaseObject
    {
        PermissionPolicyRole fRoles;
        [Indexed(@"Users", Name = @"iRolesUsers_PermissionPolicyUserUsers_PermissionPolicyRoleRoles", Unique = true)]
        [Association(@"PermissionPolicyUserUsers_PermissionPolicyRoleRolesReferencesPermissionPolicyRole")]
        public PermissionPolicyRole Roles
        {
            get { return fRoles; }
            set { SetPropertyValue<PermissionPolicyRole>(nameof(Roles), ref fRoles, value); }
        }
        PermissionPolicyUser fUsers;
        [Association(@"PermissionPolicyUserUsers_PermissionPolicyRoleRolesReferencesPermissionPolicyUser")]
        public PermissionPolicyUser Users
        {
            get { return fUsers; }
            set { SetPropertyValue<PermissionPolicyUser>(nameof(Users), ref fUsers, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>(nameof(OID), ref fOID, value); }
        }
    }

}
