//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class PermissionPolicyUser : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fStoredPassword;
        [Size(SizeAttribute.Unlimited)]
        public string StoredPassword
        {
            get { return fStoredPassword; }
            set { SetPropertyValue<string>(nameof(StoredPassword), ref fStoredPassword, value); }
        }
        bool fChangePasswordOnFirstLogon;
        public bool ChangePasswordOnFirstLogon
        {
            get { return fChangePasswordOnFirstLogon; }
            set { SetPropertyValue<bool>(nameof(ChangePasswordOnFirstLogon), ref fChangePasswordOnFirstLogon, value); }
        }
        string fUserName;
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        [Association(@"PermissionPolicyUserUsers_PermissionPolicyRoleRolesReferencesPermissionPolicyUser")]
        public XPCollection<PermissionPolicyUserUsers_PermissionPolicyRoleRoles> PermissionPolicyUserUsers_PermissionPolicyRoleRoless { get { return GetCollection<PermissionPolicyUserUsers_PermissionPolicyRoleRoles>(nameof(PermissionPolicyUserUsers_PermissionPolicyRoleRoless)); } }
    }

}
