//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Product_ProductItem : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        string fBarcode;
        [Size(50)]
        public string Barcode
        {
            get { return fBarcode; }
            set { SetPropertyValue<string>(nameof(Barcode), ref fBarcode, value); }
        }
        Library_Grade fGradeID;
        [Association(@"Product_ProductItemReferencesLibrary_Grade")]
        public Library_Grade GradeID
        {
            get { return fGradeID; }
            set { SetPropertyValue<Library_Grade>(nameof(GradeID), ref fGradeID, value); }
        }
        Library_Length fItemLengthID;
        [Association(@"Product_ProductItemReferencesLibrary_Length")]
        public Library_Length ItemLengthID
        {
            get { return fItemLengthID; }
            set { SetPropertyValue<Library_Length>(nameof(ItemLengthID), ref fItemLengthID, value); }
        }
        Product_ProductReceive fRecID;
        [Association(@"Product_ProductItemReferencesProduct_ProductReceive")]
        public Product_ProductReceive RecID
        {
            get { return fRecID; }
            set { SetPropertyValue<Product_ProductReceive>(nameof(RecID), ref fRecID, value); }
        }
        Container_Packed fPackedID;
        [Association(@"Product_ProductItemReferencesContainer_Packed")]
        public Container_Packed PackedID
        {
            get { return fPackedID; }
            set { SetPropertyValue<Container_Packed>(nameof(PackedID), ref fPackedID, value); }
        }
        ProductItemPickList fItemPickListID;
        [Association(@"Product_ProductItemReferencesProductItemPickList")]
        public ProductItemPickList ItemPickListID
        {
            get { return fItemPickListID; }
            set { SetPropertyValue<ProductItemPickList>(nameof(ItemPickListID), ref fItemPickListID, value); }
        }
        int fDispID;
        public int DispID
        {
            get { return fDispID; }
            set { SetPropertyValue<int>(nameof(DispID), ref fDispID, value); }
        }
        int fQuantity;
        public int Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<int>(nameof(Quantity), ref fQuantity, value); }
        }
        double fItemOriginGross;
        public double ItemOriginGross
        {
            get { return fItemOriginGross; }
            set { SetPropertyValue<double>(nameof(ItemOriginGross), ref fItemOriginGross, value); }
        }
        double fItemOriginNett;
        public double ItemOriginNett
        {
            get { return fItemOriginNett; }
            set { SetPropertyValue<double>(nameof(ItemOriginNett), ref fItemOriginNett, value); }
        }
        int fWBTicket;
        public int WBTicket
        {
            get { return fWBTicket; }
            set { SetPropertyValue<int>(nameof(WBTicket), ref fWBTicket, value); }
        }
        double fItemGross;
        public double ItemGross
        {
            get { return fItemGross; }
            set { SetPropertyValue<double>(nameof(ItemGross), ref fItemGross, value); }
        }
        double fItemNett;
        public double ItemNett
        {
            get { return fItemNett; }
            set { SetPropertyValue<double>(nameof(ItemNett), ref fItemNett, value); }
        }
        int fNoOfStraps;
        public int NoOfStraps
        {
            get { return fNoOfStraps; }
            set { SetPropertyValue<int>(nameof(NoOfStraps), ref fNoOfStraps, value); }
        }
        byte[] fPhoto1;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo1
        {
            get { return fPhoto1; }
            set { SetPropertyValue<byte[]>(nameof(Photo1), ref fPhoto1, value); }
        }
        string fDiametreScan;
        public string DiametreScan
        {
            get { return fDiametreScan; }
            set { SetPropertyValue<string>(nameof(DiametreScan), ref fDiametreScan, value); }
        }
        int fLogDiameter;
        public int LogDiameter
        {
            get { return fLogDiameter; }
            set { SetPropertyValue<int>(nameof(LogDiameter), ref fLogDiameter, value); }
        }
        double fVolume;
        public double Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<double>(nameof(Volume), ref fVolume, value); }
        }
        double fVolume2;
        public double Volume2
        {
            get { return fVolume2; }
            set { SetPropertyValue<double>(nameof(Volume2), ref fVolume2, value); }
        }
        DateTime fLastScanDate;
        public DateTime LastScanDate
        {
            get { return fLastScanDate; }
            set { SetPropertyValue<DateTime>(nameof(LastScanDate), ref fLastScanDate, value); }
        }
        int fBrokenStraps;
        public int BrokenStraps
        {
            get { return fBrokenStraps; }
            set { SetPropertyValue<int>(nameof(BrokenStraps), ref fBrokenStraps, value); }
        }
    }

}
