//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Product_ProductDispatch : XPLiteObject
    {
        
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Order_OrderIn fRecOrderID;
        [Association(@"Product_ProductDispatchReferencesOrder_OrderIn")]
        public Order_OrderIn RecOrderID
        {
            get { return fRecOrderID; }
            set { SetPropertyValue<Order_OrderIn>(nameof(RecOrderID), ref fRecOrderID, value); }
        }
        DateTime fDispatchDate;
        public DateTime DispatchDate
        {
            get { return fDispatchDate; }
            set { SetPropertyValue<DateTime>(nameof(DispatchDate), ref fDispatchDate, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"Product_ProductDispatchReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        string fTruckRegistration;
        [Size(50)]
        public string TruckRegistration
        {
            get { return fTruckRegistration; }
            set { SetPropertyValue<string>(nameof(TruckRegistration), ref fTruckRegistration, value); }
        }
        string fTrailer1Registration;
        [Size(50)]
        public string Trailer1Registration
        {
            get { return fTrailer1Registration; }
            set { SetPropertyValue<string>(nameof(Trailer1Registration), ref fTrailer1Registration, value); }
        }
        string fTrailer2Registration;
        [Size(50)]
        public string Trailer2Registration
        {
            get { return fTrailer2Registration; }
            set { SetPropertyValue<string>(nameof(Trailer2Registration), ref fTrailer2Registration, value); }
        }
        Library_Site fSiteID;
        [Association(@"Product_ProductDispatchReferencesLibrary_Site")]
        public Library_Site SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<Library_Site>(nameof(SiteID), ref fSiteID, value); }
        }
        DateTime fTruckStopEntryDateTime;
        public DateTime TruckStopEntryDateTime
        {
            get { return fTruckStopEntryDateTime; }
            set { SetPropertyValue<DateTime>(nameof(TruckStopEntryDateTime), ref fTruckStopEntryDateTime, value); }
        }
        DateTime fTruckStopExitDateTime;
        public DateTime TruckStopExitDateTime
        {
            get { return fTruckStopExitDateTime; }
            set { SetPropertyValue<DateTime>(nameof(TruckStopExitDateTime), ref fTruckStopExitDateTime, value); }
        }
        int fTimeInTruckStop;
        public int TimeInTruckStop
        {
            get { return fTimeInTruckStop; }
            set { SetPropertyValue<int>(nameof(TimeInTruckStop), ref fTimeInTruckStop, value); }
        }
        int fTurnaroundTime;
        public int TurnaroundTime
        {
            get { return fTurnaroundTime; }
            set { SetPropertyValue<int>(nameof(TurnaroundTime), ref fTurnaroundTime, value); }
        }
        string fAdditionalReferenceNo;
        [Size(50)]
        public string AdditionalReferenceNo
        {
            get { return fAdditionalReferenceNo; }
            set { SetPropertyValue<string>(nameof(AdditionalReferenceNo), ref fAdditionalReferenceNo, value); }
        }
        double fGrossWeight;
        public double GrossWeight
        {
            get { return fGrossWeight; }
            set { SetPropertyValue<double>(nameof(GrossWeight), ref fGrossWeight, value); }
        }
        DateTime fGrossWeightDate;
        public DateTime GrossWeightDate
        {
            get { return fGrossWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(GrossWeightDate), ref fGrossWeightDate, value); }
        }
        double fTarWeight;
        public double TarWeight
        {
            get { return fTarWeight; }
            set { SetPropertyValue<double>(nameof(TarWeight), ref fTarWeight, value); }
        }
        DateTime fTarWeightDate;
        public DateTime TarWeightDate
        {
            get { return fTarWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(TarWeightDate), ref fTarWeightDate, value); }
        }
        double fNettWeight;
        public double NettWeight
        {
            get { return fNettWeight; }
            set { SetPropertyValue<double>(nameof(NettWeight), ref fNettWeight, value); }
        }
        Library_Weighbridge fWeighbridgeID;
        [Association(@"Product_ProductDispatchReferencesLibrary_Weighbridge")]
        public Library_Weighbridge WeighbridgeID
        {
            get { return fWeighbridgeID; }
            set { SetPropertyValue<Library_Weighbridge>(nameof(WeighbridgeID), ref fWeighbridgeID, value); }
        }
        string fGeneralComments;
        [Size(SizeAttribute.Unlimited)]
        public string GeneralComments
        {
            get { return fGeneralComments; }
            set { SetPropertyValue<string>(nameof(GeneralComments), ref fGeneralComments, value); }
        }
        string fRunnerName;
        [Size(50)]
        public string RunnerName
        {
            get { return fRunnerName; }
            set { SetPropertyValue<string>(nameof(RunnerName), ref fRunnerName, value); }
        }
        string fDriverName;
        [Size(50)]
        public string DriverName
        {
            get { return fDriverName; }
            set { SetPropertyValue<string>(nameof(DriverName), ref fDriverName, value); }
        }
        string fDriverCell;
        [Size(50)]
        public string DriverCell
        {
            get { return fDriverCell; }
            set { SetPropertyValue<string>(nameof(DriverCell), ref fDriverCell, value); }
        }
        string fDispatchAddress;
        [Size(300)]
        public string DispatchAddress
        {
            get { return fDispatchAddress; }
            set { SetPropertyValue<string>(nameof(DispatchAddress), ref fDispatchAddress, value); }
        }
        string fDeliveryNote;
        [Size(50)]
        public string DeliveryNote
        {
            get { return fDeliveryNote; }
            set { SetPropertyValue<string>(nameof(DeliveryNote), ref fDeliveryNote, value); }
        }
        Library_Status fStatusID;
        [Association(@"Product_ProductDispatchReferencesLibrary_Status")]
        public Library_Status StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<Library_Status>(nameof(StatusID), ref fStatusID, value); }
        }
        string fSeal1Number;
        [Size(50)]
        public string Seal1Number
        {
            get { return fSeal1Number; }
            set { SetPropertyValue<string>(nameof(Seal1Number), ref fSeal1Number, value); }
        }
        string fSeal2Number;
        [Size(50)]
        public string Seal2Number
        {
            get { return fSeal2Number; }
            set { SetPropertyValue<string>(nameof(Seal2Number), ref fSeal2Number, value); }
        }
        int fWarehouseZoneID;
        public int WarehouseZoneID
        {
            get { return fWarehouseZoneID; }
            set { SetPropertyValue<int>(nameof(WarehouseZoneID), ref fWarehouseZoneID, value); }
        }
        int fWBTicket;
        public int WBTicket
        {
            get { return fWBTicket; }
            set { SetPropertyValue<int>(nameof(WBTicket), ref fWBTicket, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        ShuttleTrucks fShuttleID;
        [Association(@"Product_ProductDispatchReferencesShuttleTrucks")]
        public ShuttleTrucks ShuttleID
        {
            get { return fShuttleID; }
            set { SetPropertyValue<ShuttleTrucks>(nameof(ShuttleID), ref fShuttleID, value); }
        }
        byte[] fDispatchPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] DispatchPhoto
        {
            get { return fDispatchPhoto; }
            set { SetPropertyValue<byte[]>(nameof(DispatchPhoto), ref fDispatchPhoto, value); }
        }
        Invoice fInvoiceID;
        [Association(@"Product_ProductDispatchReferencesInvoice")]
        public Invoice InvoiceID
        {
            get { return fInvoiceID; }
            set { SetPropertyValue<Invoice>(nameof(InvoiceID), ref fInvoiceID, value); }
        }
        int feFlag;
        public int eFlag
        {
            get { return feFlag; }
            set { SetPropertyValue<int>(nameof(eFlag), ref feFlag, value); }
        }
        Library_TarpCondition fTarpConditionID;
        [Association(@"Product_ProductDispatchReferencesLibrary_TarpCondition")]
        public Library_TarpCondition TarpConditionID
        {
            get { return fTarpConditionID; }
            set { SetPropertyValue<Library_TarpCondition>(nameof(TarpConditionID), ref fTarpConditionID, value); }
        }
        Library_Weather fWeatherID;
        [Association(@"Product_ProductDispatchReferencesLibrary_Weather")]
        public Library_Weather WeatherID
        {
            get { return fWeatherID; }
            set { SetPropertyValue<Library_Weather>(nameof(WeatherID), ref fWeatherID, value); }
        }
        Library_SealCondition fSealConditionID;
        [Association(@"Product_ProductDispatchReferencesLibrary_SealCondition")]
        public Library_SealCondition SealConditionID
        {
            get { return fSealConditionID; }
            set { SetPropertyValue<Library_SealCondition>(nameof(SealConditionID), ref fSealConditionID, value); }
        }
        AccessControl fAccessID;
        [Association(@"Product_ProductDispatchReferencesAccessControl")]
        public AccessControl AccessID
        {
            get { return fAccessID; }
            set { SetPropertyValue<AccessControl>(nameof(AccessID), ref fAccessID, value); }
        }
        Order_OrderOut fOrderOutID;
        [Association(@"Product_ProductDispatchReferencesOrder_OrderOut")]
        public Order_OrderOut OrderOutID
        {
            get { return fOrderOutID; }
            set { SetPropertyValue<Order_OrderOut>(nameof(OrderOutID), ref fOrderOutID, value); }
        }
        Order_VesselHatch fOrderVesselHatchID;
        [Association(@"Product_ProductDispatchReferencesOrder_VesselHatch")]
        public Order_VesselHatch OrderVesselHatchID
        {
            get { return fOrderVesselHatchID; }
            set { SetPropertyValue<Order_VesselHatch>(nameof(OrderVesselHatchID), ref fOrderVesselHatchID, value); }
        }
    }

}
