//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Product_Dispatch_Rail : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Order_OrderIn fOrderID;
        [Association(@"Product_Dispatch_RailReferencesOrder_OrderIn")]
        public Order_OrderIn OrderID
        {
            get { return fOrderID; }
            set { SetPropertyValue<Order_OrderIn>(nameof(OrderID), ref fOrderID, value); }
        }
        DateTime fLoadDate;
        public DateTime LoadDate
        {
            get { return fLoadDate; }
            set { SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value); }
        }
        WagonConsignment fConsignmentID;
        [Association(@"Product_Dispatch_RailReferencesWagonConsignment")]
        public WagonConsignment ConsignmentID
        {
            get { return fConsignmentID; }
            set { SetPropertyValue<WagonConsignment>(nameof(ConsignmentID), ref fConsignmentID, value); }
        }
        int fSEQ;
        public int SEQ
        {
            get { return fSEQ; }
            set { SetPropertyValue<int>(nameof(SEQ), ref fSEQ, value); }
        }
        string fWagonNo;
        [Size(50)]
        public string WagonNo
        {
            get { return fWagonNo; }
            set { SetPropertyValue<string>(nameof(WagonNo), ref fWagonNo, value); }
        }
        double fNettMass;
        public double NettMass
        {
            get { return fNettMass; }
            set { SetPropertyValue<double>(nameof(NettMass), ref fNettMass, value); }
        }
        string fConsignmentNo;
        [Size(50)]
        public string ConsignmentNo
        {
            get { return fConsignmentNo; }
            set { SetPropertyValue<string>(nameof(ConsignmentNo), ref fConsignmentNo, value); }
        }
        string fTrainWagon;
        [Size(10)]
        public string TrainWagon
        {
            get { return fTrainWagon; }
            set { SetPropertyValue<string>(nameof(TrainWagon), ref fTrainWagon, value); }
        }
        double fTotalMass;
        public double TotalMass
        {
            get { return fTotalMass; }
            set { SetPropertyValue<double>(nameof(TotalMass), ref fTotalMass, value); }
        }
        double fMass1;
        public double Mass1
        {
            get { return fMass1; }
            set { SetPropertyValue<double>(nameof(Mass1), ref fMass1, value); }
        }
        double fMass2;
        public double Mass2
        {
            get { return fMass2; }
            set { SetPropertyValue<double>(nameof(Mass2), ref fMass2, value); }
        }
        double fTareMass;
        public double TareMass
        {
            get { return fTareMass; }
            set { SetPropertyValue<double>(nameof(TareMass), ref fTareMass, value); }
        }
        string fVehicleType2;
        [Size(30)]
        public string VehicleType2
        {
            get { return fVehicleType2; }
            set { SetPropertyValue<string>(nameof(VehicleType2), ref fVehicleType2, value); }
        }
    }

}
