//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Product_Receive_Rail : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        int fWBTicket;
        public int WBTicket
        {
            get { return fWBTicket; }
            set { SetPropertyValue<int>(nameof(WBTicket), ref fWBTicket, value); }
        }
        Order_OrderIn fOrderID;
        [Association(@"Product_Receive_RailReferencesOrder_OrderIn")]
        public Order_OrderIn OrderID
        {
            get { return fOrderID; }
            set { SetPropertyValue<Order_OrderIn>(nameof(OrderID), ref fOrderID, value); }
        }
        DateTime fLoadDate;
        public DateTime LoadDate
        {
            get { return fLoadDate; }
            set { SetPropertyValue<DateTime>(nameof(LoadDate), ref fLoadDate, value); }
        }
        WagonConsignment fConsignmentID;
        [Association(@"Product_Receive_RailReferencesWagonConsignment")]
        public WagonConsignment ConsignmentID
        {
            get { return fConsignmentID; }
            set { SetPropertyValue<WagonConsignment>(nameof(ConsignmentID), ref fConsignmentID, value); }
        }
        int fSEQ;
        public int SEQ
        {
            get { return fSEQ; }
            set { SetPropertyValue<int>(nameof(SEQ), ref fSEQ, value); }
        }
        string fWagonNo;
        [Size(50)]
        public string WagonNo
        {
            get { return fWagonNo; }
            set { SetPropertyValue<string>(nameof(WagonNo), ref fWagonNo, value); }
        }
        double fNettMass;
        public double NettMass
        {
            get { return fNettMass; }
            set { SetPropertyValue<double>(nameof(NettMass), ref fNettMass, value); }
        }
        string fConsignmentNo;
        [Size(50)]
        public string ConsignmentNo
        {
            get { return fConsignmentNo; }
            set { SetPropertyValue<string>(nameof(ConsignmentNo), ref fConsignmentNo, value); }
        }
        double fGrossWeight;
        public double GrossWeight
        {
            get { return fGrossWeight; }
            set { SetPropertyValue<double>(nameof(GrossWeight), ref fGrossWeight, value); }
        }
        DateTime fGrossWeightDate;
        public DateTime GrossWeightDate
        {
            get { return fGrossWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(GrossWeightDate), ref fGrossWeightDate, value); }
        }
        double fTarWeight;
        public double TarWeight
        {
            get { return fTarWeight; }
            set { SetPropertyValue<double>(nameof(TarWeight), ref fTarWeight, value); }
        }
        DateTime fTarWeightDate;
        public DateTime TarWeightDate
        {
            get { return fTarWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(TarWeightDate), ref fTarWeightDate, value); }
        }
        Library_ContainerSize fWagonSizeID;
        [Association(@"Product_Receive_RailReferencesLibrary_ContainerSize")]
        public Library_ContainerSize WagonSizeID
        {
            get { return fWagonSizeID; }
            set { SetPropertyValue<Library_ContainerSize>(nameof(WagonSizeID), ref fWagonSizeID, value); }
        }
        Order_VesselHatch fOrderVesselHatchID;
        [Association(@"Product_Receive_RailReferencesOrder_VesselHatch")]
        public Order_VesselHatch OrderVesselHatchID
        {
            get { return fOrderVesselHatchID; }
            set { SetPropertyValue<Order_VesselHatch>(nameof(OrderVesselHatchID), ref fOrderVesselHatchID, value); }
        }
        string fGeneralComments;
        [Size(SizeAttribute.Unlimited)]
        public string GeneralComments
        {
            get { return fGeneralComments; }
            set { SetPropertyValue<string>(nameof(GeneralComments), ref fGeneralComments, value); }
        }
        Library_Site fSiteID;
        [Association(@"Product_Receive_RailReferencesLibrary_Site")]
        public Library_Site SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<Library_Site>(nameof(SiteID), ref fSiteID, value); }
        }
        Library_Weighbridge fWeighbridgeID;
        [Association(@"Product_Receive_RailReferencesLibrary_Weighbridge")]
        public Library_Weighbridge WeighbridgeID
        {
            get { return fWeighbridgeID; }
            set { SetPropertyValue<Library_Weighbridge>(nameof(WeighbridgeID), ref fWeighbridgeID, value); }
        }
        bool fManualTicket;
        public bool ManualTicket
        {
            get { return fManualTicket; }
            set { SetPropertyValue<bool>(nameof(ManualTicket), ref fManualTicket, value); }
        }
    }

}
