//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Product_ReceiveCount : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Library_Grade fGradeID;
        [Association(@"Product_ReceiveCountReferencesLibrary_Grade")]
        public Library_Grade GradeID
        {
            get { return fGradeID; }
            set { SetPropertyValue<Library_Grade>(nameof(GradeID), ref fGradeID, value); }
        }
        Library_Length fItemLengthID;
        [Association(@"Product_ReceiveCountReferencesLibrary_Length")]
        public Library_Length ItemLengthID
        {
            get { return fItemLengthID; }
            set { SetPropertyValue<Library_Length>(nameof(ItemLengthID), ref fItemLengthID, value); }
        }
        Product_ProductReceive fRecID;
        [Association(@"Product_ReceiveCountReferencesProduct_ProductReceive")]
        public Product_ProductReceive RecID
        {
            get { return fRecID; }
            set { SetPropertyValue<Product_ProductReceive>(nameof(RecID), ref fRecID, value); }
        }
        int fQuantity;
        public int Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<int>(nameof(Quantity), ref fQuantity, value); }
        }
    }

}
