//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class ProductItemPickList : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        DateTime fPickListDate;
        public DateTime PickListDate
        {
            get { return fPickListDate; }
            set { SetPropertyValue<DateTime>(nameof(PickListDate), ref fPickListDate, value); }
        }
        string fPickListNumber;
        [Size(50)]
        public string PickListNumber
        {
            get { return fPickListNumber; }
            set { SetPropertyValue<string>(nameof(PickListNumber), ref fPickListNumber, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        string fComment;
        public string Comment
        {
            get { return fComment; }
            set { SetPropertyValue<string>(nameof(Comment), ref fComment, value); }
        }
        string fScanList;
        public string ScanList
        {
            get { return fScanList; }
            set { SetPropertyValue<string>(nameof(ScanList), ref fScanList, value); }
        }
        string fItemBarcode;
        public string ItemBarcode
        {
            get { return fItemBarcode; }
            set { SetPropertyValue<string>(nameof(ItemBarcode), ref fItemBarcode, value); }
        }
        double fListNettWeight;
        public double ListNettWeight
        {
            get { return fListNettWeight; }
            set { SetPropertyValue<double>(nameof(ListNettWeight), ref fListNettWeight, value); }
        }
        string fScanValidation;
        public string ScanValidation
        {
            get { return fScanValidation; }
            set { SetPropertyValue<string>(nameof(ScanValidation), ref fScanValidation, value); }
        }
        Order_BookingReference fBookingReferenceID;
        [Association(@"ProductItemPickListReferencesOrder_BookingReference")]
        public Order_BookingReference BookingReferenceID
        {
            get { return fBookingReferenceID; }
            set { SetPropertyValue<Order_BookingReference>(nameof(BookingReferenceID), ref fBookingReferenceID, value); }
        }
        [Association(@"Container_PackedReferencesProductItemPickList")]
        public XPCollection<Container_Packed> Container_Packeds { get { return GetCollection<Container_Packed>(nameof(Container_Packeds)); } }
        [Association(@"Product_ProductItemReferencesProductItemPickList")]
        public XPCollection<Product_ProductItem> Product_ProductItems { get { return GetCollection<Product_ProductItem>(nameof(Product_ProductItems)); } }
    }

}
