//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Product_ProductReceive : XPLiteObject
    {
       
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        Order_OrderIn fRecOrderID;
        [Association(@"Product_ProductReceiveReferencesOrder_OrderIn")]
        public Order_OrderIn RecOrderID
        {
            get { return fRecOrderID; }
            set { SetPropertyValue<Order_OrderIn>(nameof(RecOrderID), ref fRecOrderID, value); }
        }
        DateTime fArrivalDate;
        public DateTime ArrivalDate
        {
            get { return fArrivalDate; }
            set { SetPropertyValue<DateTime>(nameof(ArrivalDate), ref fArrivalDate, value); }
        }
        bool fManualTicket;
        public bool ManualTicket
        {
            get { return fManualTicket; }
            set { SetPropertyValue<bool>(nameof(ManualTicket), ref fManualTicket, value); }
        }
        DateTime fTruckStopEntryDateTime;
        public DateTime TruckStopEntryDateTime
        {
            get { return fTruckStopEntryDateTime; }
            set { SetPropertyValue<DateTime>(nameof(TruckStopEntryDateTime), ref fTruckStopEntryDateTime, value); }
        }
        DateTime fTruckStopExitDateTime;
        public DateTime TruckStopExitDateTime
        {
            get { return fTruckStopExitDateTime; }
            set { SetPropertyValue<DateTime>(nameof(TruckStopExitDateTime), ref fTruckStopExitDateTime, value); }
        }
        int fTimeInTruckStop;
        public int TimeInTruckStop
        {
            get { return fTimeInTruckStop; }
            set { SetPropertyValue<int>(nameof(TimeInTruckStop), ref fTimeInTruckStop, value); }
        }
        int fTurnaroundTime;
        public int TurnaroundTime
        {
            get { return fTurnaroundTime; }
            set { SetPropertyValue<int>(nameof(TurnaroundTime), ref fTurnaroundTime, value); }
        }
        int fSequence;
        public int Sequence
        {
            get { return fSequence; }
            set { SetPropertyValue<int>(nameof(Sequence), ref fSequence, value); }
        }
        Library_Transporter fTransporterID;
        [Association(@"Product_ProductReceiveReferencesLibrary_Transporter")]
        public Library_Transporter TransporterID
        {
            get { return fTransporterID; }
            set { SetPropertyValue<Library_Transporter>(nameof(TransporterID), ref fTransporterID, value); }
        }
        string fTruckRegistration;
        [Size(50)]
        public string TruckRegistration
        {
            get { return fTruckRegistration; }
            set { SetPropertyValue<string>(nameof(TruckRegistration), ref fTruckRegistration, value); }
        }
        string fTrailer1Registration;
        [Size(50)]
        public string Trailer1Registration
        {
            get { return fTrailer1Registration; }
            set { SetPropertyValue<string>(nameof(Trailer1Registration), ref fTrailer1Registration, value); }
        }
        string fTrailer2Registration;
        [Size(50)]
        public string Trailer2Registration
        {
            get { return fTrailer2Registration; }
            set { SetPropertyValue<string>(nameof(Trailer2Registration), ref fTrailer2Registration, value); }
        }
        Library_Site fSiteID;
        [Association(@"Product_ProductReceiveReferencesLibrary_Site")]
        public Library_Site SiteID
        {
            get { return fSiteID; }
            set { SetPropertyValue<Library_Site>(nameof(SiteID), ref fSiteID, value); }
        }
        string fOriginWeighbridgeTicketNo;
        [Size(50)]
        public string OriginWeighbridgeTicketNo
        {
            get { return fOriginWeighbridgeTicketNo; }
            set { SetPropertyValue<string>(nameof(OriginWeighbridgeTicketNo), ref fOriginWeighbridgeTicketNo, value); }
        }
        double fOriginNettWeight;
        public double OriginNettWeight
        {
            get { return fOriginNettWeight; }
            set { SetPropertyValue<double>(nameof(OriginNettWeight), ref fOriginNettWeight, value); }
        }
        string fAdditionalReferenceNo;
        [Size(10)]
        public string AdditionalReferenceNo
        {
            get { return fAdditionalReferenceNo; }
            set { SetPropertyValue<string>(nameof(AdditionalReferenceNo), ref fAdditionalReferenceNo, value); }
        }
        string fContainerNo;
        [Size(50)]
        public string ContainerNo
        {
            get { return fContainerNo; }
            set { SetPropertyValue<string>(nameof(ContainerNo), ref fContainerNo, value); }
        }
        double fGrossWeight;
        public double GrossWeight
        {
            get { return fGrossWeight; }
            set { SetPropertyValue<double>(nameof(GrossWeight), ref fGrossWeight, value); }
        }
        DateTime fGrossWeightDate;
        public DateTime GrossWeightDate
        {
            get { return fGrossWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(GrossWeightDate), ref fGrossWeightDate, value); }
        }
        double fTarWeight;
        public double TarWeight
        {
            get { return fTarWeight; }
            set { SetPropertyValue<double>(nameof(TarWeight), ref fTarWeight, value); }
        }
        DateTime fTarWeightDate;
        public DateTime TarWeightDate
        {
            get { return fTarWeightDate; }
            set { SetPropertyValue<DateTime>(nameof(TarWeightDate), ref fTarWeightDate, value); }
        }
        double fNettWeight;
        public double NettWeight
        {
            get { return fNettWeight; }
            set { SetPropertyValue<double>(nameof(NettWeight), ref fNettWeight, value); }
        }
        Library_Weighbridge fWeighbridgeID;
        [Association(@"Product_ProductReceiveReferencesLibrary_Weighbridge")]
        public Library_Weighbridge WeighbridgeID
        {
            get { return fWeighbridgeID; }
            set { SetPropertyValue<Library_Weighbridge>(nameof(WeighbridgeID), ref fWeighbridgeID, value); }
        }
        string fGeneralComments;
        [Size(SizeAttribute.Unlimited)]
        public string GeneralComments
        {
            get { return fGeneralComments; }
            set { SetPropertyValue<string>(nameof(GeneralComments), ref fGeneralComments, value); }
        }
        string fRunnerName;
        [Size(50)]
        public string RunnerName
        {
            get { return fRunnerName; }
            set { SetPropertyValue<string>(nameof(RunnerName), ref fRunnerName, value); }
        }
        string fDriverName;
        [Size(50)]
        public string DriverName
        {
            get { return fDriverName; }
            set { SetPropertyValue<string>(nameof(DriverName), ref fDriverName, value); }
        }
        string fDriverCell;
        [Size(50)]
        public string DriverCell
        {
            get { return fDriverCell; }
            set { SetPropertyValue<string>(nameof(DriverCell), ref fDriverCell, value); }
        }
        Library_Status fStatusID;
        [Association(@"Product_ProductReceiveReferencesLibrary_Status")]
        public Library_Status StatusID
        {
            get { return fStatusID; }
            set { SetPropertyValue<Library_Status>(nameof(StatusID), ref fStatusID, value); }
        }
        int fPackListID;
        public int PackListID
        {
            get { return fPackListID; }
            set { SetPropertyValue<int>(nameof(PackListID), ref fPackListID, value); }
        }
        int fItemQuantity;
        public int ItemQuantity
        {
            get { return fItemQuantity; }
            set { SetPropertyValue<int>(nameof(ItemQuantity), ref fItemQuantity, value); }
        }
        string fSeal1Number;
        [Size(50)]
        public string Seal1Number
        {
            get { return fSeal1Number; }
            set { SetPropertyValue<string>(nameof(Seal1Number), ref fSeal1Number, value); }
        }
        string fSeal2Number;
        [Size(50)]
        public string Seal2Number
        {
            get { return fSeal2Number; }
            set { SetPropertyValue<string>(nameof(Seal2Number), ref fSeal2Number, value); }
        }
        int fWarehouseZoneID;
        public int WarehouseZoneID
        {
            get { return fWarehouseZoneID; }
            set { SetPropertyValue<int>(nameof(WarehouseZoneID), ref fWarehouseZoneID, value); }
        }
        DateTime fOriginDate;
        public DateTime OriginDate
        {
            get { return fOriginDate; }
            set { SetPropertyValue<DateTime>(nameof(OriginDate), ref fOriginDate, value); }
        }
        string fOriginDeliveryNote;
        [Size(50)]
        public string OriginDeliveryNote
        {
            get { return fOriginDeliveryNote; }
            set { SetPropertyValue<string>(nameof(OriginDeliveryNote), ref fOriginDeliveryNote, value); }
        }
        int fWBTicket;
        [Indexed(Name = @"iWBTicket_Product_ProductReceive", Unique = true)]
        public int WBTicket
        {
            get { return fWBTicket; }
            set { SetPropertyValue<int>(nameof(WBTicket), ref fWBTicket, value); }
        }
        string fLastUser;
        [Size(50)]
        public string LastUser
        {
            get { return fLastUser; }
            set { SetPropertyValue<string>(nameof(LastUser), ref fLastUser, value); }
        }
        ShuttleTrucks fShuttleID;
        [Association(@"Product_ProductReceiveReferencesShuttleTrucks")]
        public ShuttleTrucks ShuttleID
        {
            get { return fShuttleID; }
            set { SetPropertyValue<ShuttleTrucks>(nameof(ShuttleID), ref fShuttleID, value); }
        }
        ExpectedTrucks fExpectedID;
        [Association(@"Product_ProductReceiveReferencesExpectedTrucks")]
        public ExpectedTrucks ExpectedID
        {
            get { return fExpectedID; }
            set { SetPropertyValue<ExpectedTrucks>(nameof(ExpectedID), ref fExpectedID, value); }
        }
        byte[] fReceivePhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] ReceivePhoto
        {
            get { return fReceivePhoto; }
            set { SetPropertyValue<byte[]>(nameof(ReceivePhoto), ref fReceivePhoto, value); }
        }
        Invoice fInvoiceID;
        [Association(@"Product_ProductReceiveReferencesInvoice")]
        public Invoice InvoiceID
        {
            get { return fInvoiceID; }
            set { SetPropertyValue<Invoice>(nameof(InvoiceID), ref fInvoiceID, value); }
        }
        int feFlag;
        public int eFlag
        {
            get { return feFlag; }
            set { SetPropertyValue<int>(nameof(eFlag), ref feFlag, value); }
        }
        Library_TarpCondition fTarpConditionID;
        [Association(@"Product_ProductReceiveReferencesLibrary_TarpCondition")]
        public Library_TarpCondition TarpConditionID
        {
            get { return fTarpConditionID; }
            set { SetPropertyValue<Library_TarpCondition>(nameof(TarpConditionID), ref fTarpConditionID, value); }
        }
        Library_Weather fWeatherID;
        [Association(@"Product_ProductReceiveReferencesLibrary_Weather")]
        public Library_Weather WeatherID
        {
            get { return fWeatherID; }
            set { SetPropertyValue<Library_Weather>(nameof(WeatherID), ref fWeatherID, value); }
        }
        Library_SealCondition fSealConditionID;
        [Association(@"Product_ProductReceiveReferencesLibrary_SealCondition")]
        public Library_SealCondition SealConditionID
        {
            get { return fSealConditionID; }
            set { SetPropertyValue<Library_SealCondition>(nameof(SealConditionID), ref fSealConditionID, value); }
        }
        Order_VesselHatch fOrderVesselHatchID;
        [Association(@"Product_ProductReceiveReferencesOrder_VesselHatch")]
        public Order_VesselHatch OrderVesselHatchID
        {
            get { return fOrderVesselHatchID; }
            set { SetPropertyValue<Order_VesselHatch>(nameof(OrderVesselHatchID), ref fOrderVesselHatchID, value); }
        }
        AccessControl fAccessID;
        [Association(@"Product_ProductReceiveReferencesAccessControl")]
        public AccessControl AccessID
        {
            get { return fAccessID; }
            set { SetPropertyValue<AccessControl>(nameof(AccessID), ref fAccessID, value); }
        }
        bool fSplitTicket;
        public bool SplitTicket
        {
            get { return fSplitTicket; }
            set { SetPropertyValue<bool>(nameof(SplitTicket), ref fSplitTicket, value); }
        }
        int fSplitWBTicket;
        public int SplitWBTicket
        {
            get { return fSplitWBTicket; }
            set { SetPropertyValue<int>(nameof(SplitWBTicket), ref fSplitWBTicket, value); }
        }
        int fNoOfStraps;
        public int NoOfStraps
        {
            get { return fNoOfStraps; }
            set { SetPropertyValue<int>(nameof(NoOfStraps), ref fNoOfStraps, value); }
        }
        string fLotNumber;
        [Size(50)]
        public string LotNumber
        {
            get { return fLotNumber; }
            set { SetPropertyValue<string>(nameof(LotNumber), ref fLotNumber, value); }
        }
        string fBillOfEntry;
        [Size(50)]
        public string BillOfEntry
        {
            get { return fBillOfEntry; }
            set { SetPropertyValue<string>(nameof(BillOfEntry), ref fBillOfEntry, value); }
        }
        double fOriginGrossWeight;
        public double OriginGrossWeight
        {
            get { return fOriginGrossWeight; }
            set { SetPropertyValue<double>(nameof(OriginGrossWeight), ref fOriginGrossWeight, value); }
        }
        DateTime fDateModified;
        public DateTime DateModified
        {
            get { return fDateModified; }
            set { SetPropertyValue<DateTime>(nameof(DateModified), ref fDateModified, value); }
        }
        Library_Supplier fSupplierID;
        [Association(@"Product_ProductReceiveReferencesLibrary_Supplier")]
        public Library_Supplier SupplierID
        {
            get { return fSupplierID; }
            set { SetPropertyValue<Library_Supplier>(nameof(SupplierID), ref fSupplierID, value); }
        }
        string fClientSeqNo;
        [Size(50)]
        public string ClientSeqNo
        {
            get { return fClientSeqNo; }
            set { SetPropertyValue<string>(nameof(ClientSeqNo), ref fClientSeqNo, value); }
        }
        string fTruckScan;
        [Size(50)]
        public string TruckScan
        {
            get { return fTruckScan; }
            set { SetPropertyValue<string>(nameof(TruckScan), ref fTruckScan, value); }
        }
        string fClientBarcodeScan;
        [Size(50)]
        public string ClientBarcodeScan
        {
            get { return fClientBarcodeScan; }
            set { SetPropertyValue<string>(nameof(ClientBarcodeScan), ref fClientBarcodeScan, value); }
        }
        string fLogScan;
        [Size(SizeAttribute.Unlimited)]
        public string LogScan
        {
            get { return fLogScan; }
            set { SetPropertyValue<string>(nameof(LogScan), ref fLogScan, value); }
        }
        string fLogCount;
        [Size(50)]
        public string LogCount
        {
            get { return fLogCount; }
            set { SetPropertyValue<string>(nameof(LogCount), ref fLogCount, value); }
        }
        string fLogList;
        [Size(SizeAttribute.Unlimited)]
        public string LogList
        {
            get { return fLogList; }
            set { SetPropertyValue<string>(nameof(LogList), ref fLogList, value); }
        }
        double fVolume;
        public double Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<double>(nameof(Volume), ref fVolume, value); }
        }
        bool fLockTran;
        public bool LockTran
        {
            get { return fLockTran; }
            set { SetPropertyValue<bool>(nameof(LockTran), ref fLockTran, value); }
        }
        string fGRN;
        public string GRN
        {
            get { return fGRN; }
            set { SetPropertyValue<string>(nameof(GRN), ref fGRN, value); }
        }
        Library_Grade fGradeID;
        [Association(@"Product_ProductReceiveReferencesLibrary_Grade")]
        public Library_Grade GradeID
        {
            get { return fGradeID; }
            set { SetPropertyValue<Library_Grade>(nameof(GradeID), ref fGradeID, value); }
        }
        string fItemBarcode;
        [Size(50)]
        public string ItemBarcode
        {
            get { return fItemBarcode; }
            set { SetPropertyValue<string>(nameof(ItemBarcode), ref fItemBarcode, value); }
        }
        string fBarcodeList;
        public string BarcodeList
        {
            get { return fBarcodeList; }
            set { SetPropertyValue<string>(nameof(BarcodeList), ref fBarcodeList, value); }
        }
        [Association(@"Product_ProductItemReferencesProduct_ProductReceive")]
        public XPCollection<Product_ProductItem> Product_ProductItems { get { return GetCollection<Product_ProductItem>(nameof(Product_ProductItems)); } }
        [Association(@"Product_ReceiveCountReferencesProduct_ProductReceive")]
        public XPCollection<Product_ReceiveCount> Product_ReceiveCounts { get { return GetCollection<Product_ReceiveCount>(nameof(Product_ReceiveCounts)); } }
    }

}
