//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WpfApp2.RapidCM_PGS_Dev
{

    public partial class Resource : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>(nameof(Oid), ref fOid, value); }
        }
        string fCaption;
        public string Caption
        {
            get { return fCaption; }
            set { SetPropertyValue<string>(nameof(Caption), ref fCaption, value); }
        }
        int fColor;
        public int Color
        {
            get { return fColor; }
            set { SetPropertyValue<int>(nameof(Color), ref fColor, value); }
        }
        [Association(@"ResourceResources_EventEventsReferencesResource")]
        public XPCollection<ResourceResources_EventEvents> ResourceResources_EventEventss { get { return GetCollection<ResourceResources_EventEvents>(nameof(ResourceResources_EventEventss)); } }
    }

}
